// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e6ca028d8dcade9b "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-B2I2MFQP.js";
import { stdin_default } from "./chunks/chunk-4NPMLM6U.js";
import { routes } from "./chunks/chunk-RDBOTDVL.js";

// virtual:cta
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tVHUkuNysZhgiUA8JtiN/5gQfdSp2AcqLGbDAhYGP/WD9I4Yvd5.js
import { jsx as _jsx4, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	ComponentViewportProvider,
	cx as cx4,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS4,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion4,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React4 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/PtxaBiSAA5V6LvrpAt6G/ukoWbbXWpuIc6Sz4vRp6/UD0eTfbk_.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 13.5 0 L 4.5 0 C 2.015 0 0 2.015 0 4.5 L 0 13.5 C 0 15.985 2.015 18 4.5 18 L 13.5 18 C 15.985 18 18 15.985 18 13.5 L 18 4.5 C 18 2.015 15.985 0 13.5 0 Z M 9 12.75 C 6.929 12.75 5.25 11.071 5.25 9 C 5.25 6.929 6.929 5.25 9 5.25 C 11.071 5.25 12.75 6.929 12.75 9 C 12.75 11.071 11.071 12.75 9 12.75 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18px" id="SuXKGhab5" transform="translate(3 3)" width="18px"/><path d="M 4.5 18 C 2.015 18 0 15.985 0 13.5 L 0 4.5 C 0 2.015 2.015 0 4.5 0 L 13.5 0 C 15.985 0 18 2.015 18 4.5 L 18 13.5 C 18 15.985 15.985 18 13.5 18 Z" fill="transparent" height="18px" id="vvJ8FLDVj" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 3)" width="18px"/><path d="M 0 3.75 C 0 1.679 1.679 0 3.75 0 C 5.821 0 7.5 1.679 7.5 3.75 C 7.5 5.821 5.821 7.5 3.75 7.5 C 1.679 7.5 0 5.821 0 3.75 Z" fill="transparent" height="7.5px" id="Q3v7fjWhv" stroke-dasharray="" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(8.25 8.25)" width="7.5px"/><path d="M 0 1.125 C 0 0.504 0.504 0 1.125 0 C 1.746 0 2.25 0.504 2.25 1.125 C 2.25 1.746 1.746 2.25 1.125 2.25 C 0.504 2.25 0 1.746 0 1.125 Z" fill="var(--21h8s6, rgb(0, 0, 0))" height="2.25px" id="VxeO4Hprj" transform="translate(15.75 6)" width="2.25px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("942143898", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-AT1Ex", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css2 = [".framer-AT1Ex { aspect-ratio: 1; display: block; width: 24px; }"];
var Icon = withCSS(Component, css2, "framer-AT1Ex");
Icon.displayName = "Instagram Logo";
var stdin_default2 = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/Y0c19ostjQ6JrIrS9EpB/ZlMPPV0G0dewn2RXQ7S7/QDC8_m4BS.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	motion as motion2,
	useSVGTemplate as useSVGTemplate2,
	withCSS as withCSS2,
} from "unframer";
import * as React2 from "react";
import { forwardRef as forwardRef4 } from "react";
var Base2 = /* @__PURE__ */ forwardRef4(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG2 = motion2.create(Base2);
var SVG2 = /* @__PURE__ */ forwardRef4((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG2 {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG2>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg2 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 9 C 0 4.029 4.029 0 9 0 C 13.971 0 18 4.029 18 9 C 18 13.971 13.971 18 9 18 C 4.029 18 0 13.971 0 9 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18px" id="toDPs7Y9O" transform="translate(3 3)" width="18px"/><path d="M 0 9 C 0 4.029 4.029 0 9 0 C 13.971 0 18 4.029 18 9 C 18 13.971 13.971 18 9 18 C 4.029 18 0 13.971 0 9 Z" fill="transparent" height="18px" id="nB8qhy58t" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 3)" width="18px"/><path d="M 3.75 0 L 2.25 0 C 1.007 0 0 1.007 0 2.25 L 0 12.75" fill="transparent" height="12.75px" id="QFOnXWoYe" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(12 8.25)" width="3.75px"/><path d="M 0 0 L 6 0" fill="transparent" height="1px" id="rOK6Xhani" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(9 13.5)" width="6px"/></svg>';
var getProps2 = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps2(props);
	const href = useSVGTemplate2("1426455308", svg2);
	return (
		<SVG2
			{...restProps}
			className={cx2("framer-ojcNP", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG2>
	);
});
var css3 = [".framer-ojcNP { aspect-ratio: 1; display: block; width: 24px; }"];
var Icon2 = withCSS2(Component2, css3, "framer-ojcNP");
Icon2.displayName = "Facebook Logo";
var stdin_default3 = Icon2;
addPropertyControls2(Icon2, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType2.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType2.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType2.Number,
	},
});

// /:https://framerusercontent.com/modules/cuzxw3YvBzJq3sm0puns/eEMB6pzr9ouL7ZuuMEFc/HRa_2U6GS.js
import { jsx as _jsx3 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
	cx as cx3,
	Instance,
	Link,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS3,
} from "unframer";
import { LayoutGroup, motion as motion3, MotionConfigContext } from "unframer";
import * as React3 from "react";
import { useRef } from "react";
var enabledGestures = {
	EptH6fZjc: {
		hover: true,
	},
};
var serializationHash = "framer-3x6AT";
var variantClassNames = {
	EptH6fZjc: "framer-v-cmqdzy",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion3.create(React3.Fragment);
var getProps3 = ({ height, icon, id, link, width, ...props }) => {
	return {
		...props,
		RhBoiefR8: icon ?? props.RhBoiefR8 ?? stdin_default,
		YdTA2k7Lp: link ?? props.YdTA2k7Lp,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		RhBoiefR8,
		YdTA2k7Lp,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "EptH6fZjc",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx3(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={YdTA2k7Lp}
						motionChild={true}
						nodeId={"EptH6fZjc"}
						openInNewTab={true}
						scopeId={"HRa_2U6GS"}
					>
						<motion3.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx3(scopingClassNames, "framer-cmqdzy", className2, classNames)} framer-fgygfz`}
							data-framer-name={"primary"}
							layoutDependency={layoutDependency}
							layoutId={"EptH6fZjc"}
							ref={refBinding}
							style={{
								borderBottomLeftRadius: 201,
								borderBottomRightRadius: 201,
								borderTopLeftRadius: 201,
								borderTopRightRadius: 201,
								...style,
							}}
							{...addPropertyOverrides(
								{
									"EptH6fZjc-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<Instance
								animated={true}
								className={"framer-zheq7"}
								Component={RhBoiefR8}
								layoutDependency={layoutDependency}
								layoutId={"MKWP5APPT"}
								style={{
									"--1m6trwb": 0,
									"--21h8s6":
										"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
									"--pgex8v": 1.5,
									opacity: 0.5,
								}}
								variants={{
									"EptH6fZjc-hover": {
										opacity: 1,
									},
								}}
							/>
						</motion3.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-3x6AT.framer-fgygfz, .framer-3x6AT .framer-fgygfz { display: block; }",
	".framer-3x6AT.framer-cmqdzy { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-3x6AT .framer-zheq7 { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
];
var FramerHRa_2U6GS = withCSS3(Component3, css4, "framer-3x6AT");
var stdin_default4 = FramerHRa_2U6GS;
FramerHRa_2U6GS.displayName = "Elements/social media";
FramerHRa_2U6GS.defaultProps = {
	height: 40,
	width: 40,
};
addPropertyControls3(FramerHRa_2U6GS, {
	RhBoiefR8: {
		defaultValue: {
			identifier:
				"module:oMiuMYAdxzz5yk7pBqrm/FToqm3dwiHuJofBRASRI/Xx_sbLkzD.js:default",
			moduleId: "oMiuMYAdxzz5yk7pBqrm",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon",
		type: ControlType3.VectorSetItem,
	},
	YdTA2k7Lp: {
		title: "Link",
		type: ControlType3.Link,
	},
});
addFonts(
	FramerHRa_2U6GS,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/tVHUkuNysZhgiUA8JtiN/5gQfdSp2AcqLGbDAhYGP/WD9I4Yvd5.js
var RichTextWithFX = withFX(RichText);
var ElementsSocialMediaFonts = getFonts(stdin_default4);
var serializationHash2 = "framer-ayYbO";
var variantClassNames2 = {
	YX9SXGeLV: "framer-v-1s1wz57",
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition2 = {
	damping: 60,
	delay: 0.4,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transition3 = {
	damping: 60,
	delay: 0.5,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
var transition4 = {
	damping: 60,
	delay: 0.6,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion4.create(React4.Fragment);
var getProps4 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps4(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "YX9SXGeLV",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx4(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion4.div
						{...restProps}
						{...gestureHandlers}
						className={cx4(
							scopingClassNames,
							"framer-1s1wz57",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"YX9SXGeLV"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<RichTextWithFX
							__framer__animate={{
								transition: transition2,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__fromCanvasComponent={true}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-1cm7feb"}
							data-framer-name={"Let\u2019s Stay Connected"}
							fonts={["Inter-Medium", "GF;Instrument Serif-italic"]}
							layoutDependency={layoutDependency}
							layoutId={"dx1MYW0Uc"}
							style={{
								"--extracted-1of0zx5":
									"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
								"--framer-paragraph-spacing": "0px",
							}}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React4.Fragment>
								<motion4.h2
									style={{
										"--font-selector": "SW50ZXItTWVkaXVt",
										"--framer-font-size": "44px",
										"--framer-font-weight": "500",
										"--framer-text-alignment": "center",
										"--framer-text-color":
											"var(--extracted-1of0zx5, var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230)))",
									}}
								>
									<motion4.span
										data-text-fill={"true"}
										style={{
											backgroundImage:
												"linear-gradient(161deg, var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230)) 51.657657657657666%, var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13)) 166%)",
										}}
									>
										{"Ready to Automate Smarter? Let\u2019s "}
										<motion4.span
											style={{
												"--font-selector":
													"R0Y7SW5zdHJ1bWVudCBTZXJpZi1pdGFsaWM=",
												"--framer-font-family":
													'"Instrument Serif", "Instrument Serif Placeholder", serif',
												"--framer-font-style": "italic",
												"--framer-font-weight": "400",
											}}
										>
											{"Build Together"}
										</motion4.span>
									</motion4.span>
								</motion4.h2>
							</React4.Fragment>
						</RichTextWithFX>
						<RichTextWithFX
							__framer__animate={{
								transition: transition3,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__fromCanvasComponent={true}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-ga0n92"}
							data-framer-name={
								"Stay Updated on our future resources and course releases etc.."
							}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"D7cTqutzI"}
							style={{
								"--framer-paragraph-spacing": "0px",
							}}
							transformTemplate={transformTemplate2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React4.Fragment>
								<motion4.p
									className={"framer-styles-preset-1kvyxmc"}
									data-styles-preset={"n7RLEGRKm"}
									style={{
										"--framer-text-alignment": "center",
									}}
								>
									{"Schedule a Call and Begin Automating"}
								</motion4.p>
							</React4.Fragment>
						</RichTextWithFX>
						<ComponentViewportProvider
							height={40}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 378) -
								90
							}
						>
							<SmartComponentScopedContainer
								className={"framer-s643rq-container"}
								layoutDependency={layoutDependency}
								layoutId={"OiXa5QqQx-container"}
								nodeId={"OiXa5QqQx"}
								rendersWithMotion={true}
								scopeId={"WD9I4Yvd5"}
							>
								{_jsx4(stdin_default4, {
									height: "100%",
									id: "OiXa5QqQx",
									layoutId: "OiXa5QqQx",
									RhBoiefR8: stdin_default,
									width: "100%",
									YdTA2k7Lp: "https://x.com/home",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion4.div
							className={"framer-136z44b"}
							data-framer-name={"separation"}
							layoutDependency={layoutDependency}
							layoutId={"jkS6YYodV"}
							style={{
								backgroundColor:
									"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(255, 255, 255, 0.07))",
							}}
						/>
						<ComponentViewportProvider
							height={40}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 378) -
								90
							}
						>
							<SmartComponentScopedContainer
								className={"framer-9fi7s2-container"}
								layoutDependency={layoutDependency}
								layoutId={"uEyo1Gc_p-container"}
								nodeId={"uEyo1Gc_p"}
								rendersWithMotion={true}
								scopeId={"WD9I4Yvd5"}
								transformTemplate={transformTemplate1}
							>
								{_jsx4(stdin_default4, {
									height: "100%",
									id: "uEyo1Gc_p",
									layoutId: "uEyo1Gc_p",
									RhBoiefR8: stdin_default2,
									width: "100%",
									YdTA2k7Lp: "https://www.instagram.com/",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion4.div
							className={"framer-bpcm47"}
							data-framer-name={"separation"}
							layoutDependency={layoutDependency}
							layoutId={"KrLCdmVRt"}
							style={{
								backgroundColor:
									"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(255, 255, 255, 0.07))",
							}}
						/>
						<ComponentViewportProvider
							height={40}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 378) -
								90
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1vt09yt-container"}
								layoutDependency={layoutDependency}
								layoutId={"WAAPZu66a-container"}
								nodeId={"WAAPZu66a"}
								rendersWithMotion={true}
								scopeId={"WD9I4Yvd5"}
							>
								{_jsx4(stdin_default4, {
									height: "100%",
									id: "WAAPZu66a",
									layoutId: "WAAPZu66a",
									RhBoiefR8: stdin_default3,
									width: "100%",
									YdTA2k7Lp: "https://www.facebook.com/",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<RichTextWithFX
							__framer__animate={{
								transition: transition4,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__fromCanvasComponent={true}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-1u3e8n"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"leQlIWY1y"}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React4.Fragment>
								<motion4.p
									className={"framer-styles-preset-1kvyxmc"}
									data-styles-preset={"n7RLEGRKm"}
									style={{
										"--framer-text-alignment": "center",
									}}
								>
									{"landio@support.com"}
								</motion4.p>
							</React4.Fragment>
						</RichTextWithFX>
						<motion4.div
							className={"framer-18yedrc"}
							data-framer-name={"line"}
							layoutDependency={layoutDependency}
							layoutId={"iM2g4gG0V"}
							style={{
								background:
									"linear-gradient(90deg, var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(0, 0, 0)) 0%, var(--token-a85af9cb-7834-4006-a277-2dd1295ae376, rgb(255, 255, 255)) 100%)",
								opacity: 0.5,
							}}
						/>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-9r95ms"}
							fonts={["Inter", "Inter-Italic"]}
							layoutDependency={layoutDependency}
							layoutId={"w_4HGVE1e"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React4.Fragment>
								<motion4.p
									className={"framer-styles-preset-1kvyxmc"}
									data-styles-preset={"n7RLEGRKm"}
								>
									<motion4.em>{"Reach out anytime"}</motion4.em>
								</motion4.p>
							</React4.Fragment>
						</RichText>
						<motion4.div
							className={"framer-1cakg1m"}
							data-framer-name={"line"}
							layoutDependency={layoutDependency}
							layoutId={"xDpSlaREa"}
							style={{
								background:
									"linear-gradient(270deg, var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(0, 0, 0)) 0%, var(--token-a85af9cb-7834-4006-a277-2dd1295ae376, rgb(255, 255, 255)) 100%)",
								opacity: 0.5,
							}}
						/>
					</motion4.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ayYbO.framer-1yp8jwv, .framer-ayYbO .framer-1yp8jwv { display: block; }",
	".framer-ayYbO.framer-1s1wz57 { height: 378px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1120px; }",
	".framer-ayYbO .framer-1cm7feb { flex: none; height: auto; left: 50%; position: absolute; top: 42px; white-space: pre-wrap; width: 613px; word-break: break-word; word-wrap: break-word; }",
	".framer-ayYbO .framer-ga0n92 { flex: none; height: auto; left: 50%; position: absolute; top: 47%; white-space: pre-wrap; width: 460px; word-break: break-word; word-wrap: break-word; }",
	".framer-ayYbO .framer-s643rq-container { bottom: 50px; flex: none; height: auto; left: 434px; position: absolute; width: auto; }",
	".framer-ayYbO .framer-136z44b { bottom: 58px; flex: none; height: 24px; left: calc(45.26785714285717% - 2px / 2); overflow: hidden; position: absolute; width: 2px; }",
	".framer-ayYbO .framer-9fi7s2-container { bottom: 50px; flex: none; height: auto; left: 50%; position: absolute; width: auto; }",
	".framer-ayYbO .framer-bpcm47 { bottom: 58px; flex: none; height: 24px; left: calc(54.73214285714288% - 2px / 2); overflow: hidden; position: absolute; width: 2px; }",
	".framer-ayYbO .framer-1vt09yt-container { bottom: 50px; flex: none; height: auto; left: 646px; position: absolute; width: auto; }",
	".framer-ayYbO .framer-1u3e8n { bottom: 0px; flex: none; height: auto; left: 0px; position: absolute; right: 0px; white-space: pre-wrap; word-break: break-word; word-wrap: break-word; }",
	".framer-ayYbO .framer-18yedrc { flex: none; height: 1px; left: 407px; overflow: hidden; position: absolute; top: 12px; width: 69px; }",
	".framer-ayYbO .framer-9r95ms { flex: none; height: auto; left: 50%; position: absolute; top: 0px; white-space: pre; width: auto; }",
	".framer-ayYbO .framer-1cakg1m { flex: none; height: 1px; left: 644px; overflow: hidden; position: absolute; top: 12px; width: 69px; }",
	...css,
];
var FramerWD9I4Yvd5 = withCSS4(Component4, css5, "framer-ayYbO");
var stdin_default5 = FramerWD9I4Yvd5;
FramerWD9I4Yvd5.displayName = "cta";
FramerWD9I4Yvd5.defaultProps = {
	height: 378,
	width: 1120,
};
addFonts2(
	FramerWD9I4Yvd5,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Instrument Serif",
					source: "google",
					style: "italic",
					uiFamilyName: "Instrument Serif",
					url: "https://fonts.gstatic.com/s/instrumentserif/v5/jizHRFtNs2ka5fXjeivQ4LroWlx-6zATjnTNgNq55w.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
					weight: "400",
				},
			],
		},
		...ElementsSocialMediaFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cta
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e6ca028d8dcade9bd82279484f423380160c521ae9704eaaee26e5448359232b"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e6ca028d8dcade9bd82279484f423380160c521ae9704eaaee26e5448359232b"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var cta_default = ComponentWithRoot;
export { cta_default as default };
