// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e6ca028d8dcade9b "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-B2I2MFQP.js";
import { stdin_default, stdin_default2 } from "./chunks/chunk-WVI4X3VG.js";
import { routes } from "./chunks/chunk-RDBOTDVL.js";

// virtual:cta-section
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/xoYBU8gDBmvqMMbrUyTD/HOx7zIeKjQptpSg8sjsx/ZjS3Yh4jr.js
import { jsx as _jsx6, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	ComponentViewportProvider,
	cx as cx5,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS5,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion5,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React5 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/23UrxbLkcrqFJNnNZtF1/aLljiuATE5FcYEihCdBz/Y4J94WC46.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps = ({ fill, height, id, width, ...props }) => {
	return {
		...props,
		ezTt3ayMo: fill ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ezTt3ayMo,
		...restProps
	} = getProps(props);
	return (
		<SVG
			{...restProps}
			className={cx("framer-fIGy1", className2)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--21h8s6": ezTt3ayMo,
				...style,
			}}
		/>
	);
});
var css2 = [
	`.framer-fIGy1 { aspect-ratio: 1; background-color: var(--21h8s6); mask-image: url('data:image/svg+xml,<svg aria-label="Arrow Up Right" display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 13.5 0.75 L 13.5 10.5 C 13.5 10.914 13.165 11.25 12.75 11.25 C 12.336 11.25 12 10.914 12 10.5 L 12 2.56 L 1.281 13.281 C 0.988 13.574 0.513 13.574 0.22 13.281 C -0.073 12.988 -0.073 12.512 0.22 12.219 L 10.94 1.5 L 3 1.5 C 2.586 1.5 2.25 1.164 2.25 0.75 C 2.25 0.336 2.586 0 3 0 L 12.75 0 C 13.165 0 13.5 0.336 13.5 0.75 Z" fill="var(--21h8s6, rgb(0,0,0))" height="13.500417071534685px" id="e9ZRAF41a" opacity="1" transform="translate(5.25 5.25)" width="13.500417071534343px"/></svg>'); mask-position: center; mask-repeat: no-repeat; width: 24px; }`,
];
var Icon = withCSS(Component, css2, "framer-fIGy1");
var stdin_default3 = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Fill",
		type: ControlType.Color,
	},
});

// /:https://framerusercontent.com/modules/PtxaBiSAA5V6LvrpAt6G/ukoWbbXWpuIc6Sz4vRp6/UD0eTfbk_.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	motion as motion2,
	useSVGTemplate,
	withCSS as withCSS2,
} from "unframer";
import * as React2 from "react";
import { forwardRef as forwardRef4 } from "react";
var Base = /* @__PURE__ */ forwardRef4(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion2.create(Base);
var SVG2 = /* @__PURE__ */ forwardRef4((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 13.5 0 L 4.5 0 C 2.015 0 0 2.015 0 4.5 L 0 13.5 C 0 15.985 2.015 18 4.5 18 L 13.5 18 C 15.985 18 18 15.985 18 13.5 L 18 4.5 C 18 2.015 15.985 0 13.5 0 Z M 9 12.75 C 6.929 12.75 5.25 11.071 5.25 9 C 5.25 6.929 6.929 5.25 9 5.25 C 11.071 5.25 12.75 6.929 12.75 9 C 12.75 11.071 11.071 12.75 9 12.75 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18px" id="SuXKGhab5" transform="translate(3 3)" width="18px"/><path d="M 4.5 18 C 2.015 18 0 15.985 0 13.5 L 0 4.5 C 0 2.015 2.015 0 4.5 0 L 13.5 0 C 15.985 0 18 2.015 18 4.5 L 18 13.5 C 18 15.985 15.985 18 13.5 18 Z" fill="transparent" height="18px" id="vvJ8FLDVj" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 3)" width="18px"/><path d="M 0 3.75 C 0 1.679 1.679 0 3.75 0 C 5.821 0 7.5 1.679 7.5 3.75 C 7.5 5.821 5.821 7.5 3.75 7.5 C 1.679 7.5 0 5.821 0 3.75 Z" fill="transparent" height="7.5px" id="Q3v7fjWhv" stroke-dasharray="" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(8.25 8.25)" width="7.5px"/><path d="M 0 1.125 C 0 0.504 0.504 0 1.125 0 C 1.746 0 2.25 0.504 2.25 1.125 C 2.25 1.746 1.746 2.25 1.125 2.25 C 0.504 2.25 0 1.746 0 1.125 Z" fill="var(--21h8s6, rgb(0, 0, 0))" height="2.25px" id="VxeO4Hprj" transform="translate(15.75 6)" width="2.25px"/></svg>';
var getProps2 = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps2(props);
	const href = useSVGTemplate("942143898", svg);
	return (
		<SVG2
			{...restProps}
			className={cx2("framer-AT1Ex", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG2>
	);
});
var css3 = [".framer-AT1Ex { aspect-ratio: 1; display: block; width: 24px; }"];
var Icon2 = withCSS2(Component2, css3, "framer-AT1Ex");
Icon2.displayName = "Instagram Logo";
var stdin_default4 = Icon2;
addPropertyControls2(Icon2, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType2.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType2.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType2.Number,
	},
});

// /:https://framerusercontent.com/modules/wb6ZrZlCLNQ5HHBJtNND/c1GLxCsQBQvlLXhkz7er/Particles.js
import { jsx as _jsx3 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
	Color,
	RenderTarget,
} from "unframer";
import Particles from "react-tsparticles";
import { loadFull } from "tsparticles";
import { useCallback } from "react";
function ParticleWrapper(props) {
	const {
		background,
		color,
		radius,
		number,
		densityOptions,
		sizeOptions,
		opacityOptions,
		linksOptions,
		modeOptions,
		moveOptions,
		shapeOptions,
		clickOptions,
		hoverOptions,
		rotateOptions,
		particlesID,
		fpsOptions,
		colors,
	} = props;
	const { densityEnable, densityArea, densityFactor } = densityOptions;
	const { linksEnabled, linksColor, linksOpacity, linksDistance, linksWidth } =
		linksOptions;
	const { size, sizeType, sizeMin, sizeMax } = sizeOptions;
	const { opacity, opacityType, opacityMin, opacityMax } = opacityOptions;
	const {
		connectDistance,
		connectRadius,
		connectLinksOpacity,
		grabDistance,
		grabLinksOpacity,
		bubbleDistance,
		bubbleSize,
		bubbleDuration,
		repulseDistance,
		repulseDuration,
		pushQuantity,
		removeQuantity,
		trailQuantity,
		trailDelay,
	} = modeOptions;
	const {
		moveEnabled,
		moveDirection,
		moveSpeed,
		moveRandom,
		moveStraight,
		moveOut,
		moveVibrate,
		moveGravityEnabled,
		moveGravityAcceleration,
		moveGravityMaxSpeed,
		moveTrailEnabled,
		moveTrailAmount,
		moveSpinEnabled,
		moveSpinAcceleration,
		moveAttractEnabled,
		moveAttractDistance,
	} = moveOptions;
	const { shapeType, characterType, imageSource, imageWidth, imageHeight } =
		shapeOptions;
	const { clickEnabled, clickModes } = clickOptions;
	const { hoverEnabled, hoverModes, hoverParallax, hoverForce, hoverSmooth } =
		hoverOptions;
	const {
		rotateDirection,
		rotateValue,
		rotateAnimation,
		rotateSpeed,
		rotateSync,
	} = rotateOptions;
	const particlesInit = useCallback(async (engine) => {
		await loadFull(engine);
	}, []);
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const hasMultipleColors = colors.length > 0;
	return (
		<div
			style={{
				width: "100%",
				height: "100%",
				overflow: "hidden",
				backgroundColor: background,
				transform: "translateZ(0)",
				borderRadius: radius,
				position: "relative",
			}}
		>
			<Particles
				id={particlesID}
				init={particlesInit}
				style={{
					width: "100%",
					height: "100%",
					position: "absolute",
				}}
				options={{
					// autoPlay: !isCanvas,
					background: {
						color: {
							value: "transparent",
						},
					},
					fpsLimit: isCanvas ? 1 : fpsOptions,
					fullScreen: false,
					pauseOnBlur: true,
					pauseOnOutsideViewport: true,
					interactivity: isCanvas
						? {}
						: {
							events: {
								resize: true,
								onClick: {
									enable: isCanvas ? false : clickEnabled,
									mode: clickModes,
								},
								onHover: {
									enable: isCanvas ? false : hoverEnabled,
									mode: hoverModes,
									parallax: {
										enable: isCanvas
											? false
											: hoverEnabled
												? hoverParallax
												: false,
										force: hoverForce,
										smooth: hoverForce,
									},
								},
							},
							modes: {
								connect: {
									distance: connectDistance,
									radius: connectRadius,
									links: {
										opacity: connectLinksOpacity,
									},
								},
								grab: {
									distance: grabDistance,
									links: {
										opacity: grabLinksOpacity,
									},
								},
								bubble: {
									distance: bubbleDistance,
									size: bubbleSize,
									duration: bubbleDuration,
								},
								repulse: {
									distance: repulseDistance,
									duration: repulseDuration,
								},
								push: {
									quantity: pushQuantity,
								},
								remove: {
									quantity: removeQuantity,
								},
								trail: {
									delay: trailDelay,
									quantity: trailQuantity,
								},
							},
						},
					particles: {
						color: {
							value: hasMultipleColors
								? colors.map((color2) => makeHex(color2))
								: makeHex(color),
						},
						collisions: {
							enable: false,
						},
						rotate: {
							direction: rotateDirection,
							value: rotateValue,
							animation: !isCanvas && {
								enable: rotateAnimation,
								speed: rotateSpeed,
							},
						},
						move: {
							direction: moveDirection,
							outMode: moveOut,
							enable: isCanvas ? false : moveEnabled,
							random: moveRandom,
							speed: moveSpeed,
							straight: moveStraight,
							trail: {
								enable: moveTrailEnabled,
								length: moveTrailAmount,
							},
							spin: {
								enable: moveSpinEnabled,
								acceleration: moveSpinAcceleration,
							},
							attract: {
								enable: moveAttractEnabled,
								distance: moveAttractDistance,
							},
							gravity: {
								enable: moveGravityEnabled,
								acceleration: moveGravityAcceleration,
								maxSpeed: moveGravityMaxSpeed,
							},
							vibrate: moveVibrate,
						},
						links: {
							enable: linksEnabled,
							color: makeHex(linksColor),
							opacity: linksOpacity,
							distance: linksDistance,
							width: linksWidth,
						},
						number: {
							value: number,
							density: {
								enable: densityEnable,
								area: densityEnable && densityArea,
								factor: densityEnable && densityFactor,
							},
						},
						opacity: {
							value: opacityType
								? opacity
								: {
									min: opacityMin,
									max: opacityMax,
								},
						},
						shape: {
							type: shapeType,
							character: {
								value: characterType,
							},
							image: {
								src: imageSource,
								width: imageWidth,
								height: imageHeight,
							},
						},
						size: {
							value: sizeType
								? size
								: {
									min: sizeMin,
									max: sizeMax,
								},
						},
					},
					detectRetina: true,
				}}
			/>
		</div>
	);
}
ParticleWrapper.defaultProps = {
	background: "#000000",
	color: "#ffffff",
	radius: 0,
	number: 100,
	densityOptions: {
		densityEnable: false,
		densityArea: 5e3,
		densityFactor: 50,
	},
	sizeOptions: {
		sizeType: true,
		size: 1,
		sizeMin: 1,
		sizeMax: 10,
	},
	opacityOptions: {
		opacityType: true,
		opacity: 1,
		opacityMin: 0,
		opacityMax: 1,
	},
	linksOptions: {
		linksEnabled: false,
		linksColor: "#ffffff",
		linksOpacity: 0.2,
		linksDistance: 100,
		linksWidth: 1,
	},
	modeOptions: {
		connectDistance: 100,
		connectRadius: 50,
		connectLinksOpacity: 0.2,
		grabDistance: 100,
		grabLinksOpacity: 0.2,
		bubbleDistance: 100,
		bubbleSize: 40,
		bubbleDuration: 0.4,
		repulseDistance: 200,
		repulseDuration: 1.2,
		pushQuantity: 4,
		removeQuantity: 4,
		trailDelay: 0.1,
		trailQuantity: 10,
	},
	moveOptions: {
		moveEnabled: true,
		moveDirection: "none",
		moveSpeed: 1,
		moveRandom: false,
		moveStraight: false,
		moveOut: "out",
		moveVibrate: false,
		moveGravityEnabled: false,
		moveGravityAcceleration: 1,
		moveGravityMaxSpeed: 2,
		moveTrailEnabled: false,
		moveTrailAmount: 100,
		moveSpinEnabled: false,
		moveSpinAcceleration: 1,
		moveAttractEnabled: false,
		moveAttractDistance: 100,
	},
	shapeOptions: {
		shapeType: "circle",
		characterType: "\u{1F60E}",
		imageWidth: 100,
		imageHeight: 100,
	},
	clickOptions: {
		clickEnabled: false,
		clickModes: "push",
	},
	hoverOptions: {
		hoverEnabled: true,
		hoverModes: "none",
		hoverParallax: true,
		hoverForce: 10,
		hoverSmooth: 10,
	},
	rotateOptions: {
		rotateDirection: "random",
		rotateValue: 0,
		rotateAnimation: false,
		rotateSpeed: 5,
		rotateSync: false,
	},
	particlesID: "Unique ID",
	colors: [],
};
ParticleWrapper.displayName = "Particles";
addPropertyControls3(ParticleWrapper, {
	background: {
		type: ControlType3.Color,
		defaultValue: ParticleWrapper.defaultProps.background,
		title: "Backdrop",
	},
	color: {
		type: ControlType3.Color,
		defaultValue: ParticleWrapper.defaultProps.color,
		title: "Color",
	},
	colors: {
		type: ControlType3.Array,
		control: {
			type: ControlType3.Color,
		},
		defaultValue: ParticleWrapper.defaultProps.colors,
	},
	fpsOptions: {
		type: ControlType3.Enum,
		title: "FPS",
		options: [30, 60, 120],
		optionTitles: ["30", "60", "120"],
		defaultValue: 60,
		displaySegmentedControl: true,
	},
	number: {
		type: ControlType3.Number,
		title: "Amount",
		min: 0,
		max: 1e3,
		step: 1,
		defaultValue: ParticleWrapper.defaultProps.number,
	},
	densityOptions: {
		type: ControlType3.Object,
		title: "Density",
		controls: {
			densityEnable: {
				type: ControlType3.Boolean,
				title: "Enable",
				defaultValue: ParticleWrapper.defaultProps.densityOptions.densityEnable,
			},
			densityArea: {
				type: ControlType3.Number,
				title: "Area",
				min: 100,
				max: 1e4,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.densityOptions.densityArea,
				hidden: (props) => !props.densityEnable,
			},
			densityFactor: {
				type: ControlType3.Number,
				title: "Factor",
				min: 0,
				max: 100,
				step: 0.5,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.densityOptions.densityFactor,
				description:
					"Decrease the amount property when using these, as too many particles in dense areas can cause slowdowns.",
				hidden: (props) => !props.densityEnable,
			},
		},
	},
	sizeOptions: {
		type: ControlType3.Object,
		title: "Size",
		controls: {
			sizeType: {
				type: ControlType3.Boolean,
				title: "Type",
				enabledTitle: "Value",
				disabledTitle: "Range",
				defaultValue: ParticleWrapper.defaultProps.sizeOptions.sizeType,
			},
			size: {
				type: ControlType3.Number,
				title: "Size",
				min: 0,
				max: 1e3,
				step: 0.5,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.sizeOptions.size,
				hidden: (props) => !props.sizeType,
			},
			sizeMin: {
				type: ControlType3.Number,
				title: "Min",
				min: 0,
				max: 1e3,
				step: 0.5,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.sizeOptions.sizeMin,
				hidden: (props) => props.sizeType,
			},
			sizeMax: {
				type: ControlType3.Number,
				title: "Max",
				min: 0,
				max: 1e3,
				step: 0.5,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.sizeOptions.sizeMax,
				hidden: (props) => props.sizeType,
			},
		},
	},
	opacityOptions: {
		type: ControlType3.Object,
		title: "Opacity",
		controls: {
			opacityType: {
				type: ControlType3.Boolean,
				title: "Type",
				enabledTitle: "Value",
				disabledTitle: "Range",
				defaultValue: ParticleWrapper.defaultProps.opacityOptions.opacityType,
			},
			opacity: {
				type: ControlType3.Number,
				title: "Opacity",
				min: 0,
				max: 1,
				step: 0.1,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.opacityOptions.opacity,
				hidden: (props) => !props.opacityType,
			},
			opacityMin: {
				type: ControlType3.Number,
				title: "Min",
				min: 0,
				max: 1,
				step: 0.05,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.opacityOptions.opacityMin,
				hidden: (props) => props.opacityType,
			},
			opacityMax: {
				type: ControlType3.Number,
				title: "Max",
				min: 0,
				max: 1,
				step: 0.05,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.opacityOptions.opacityMax,
				hidden: (props) => props.opacityType,
			},
		},
	},
	linksOptions: {
		type: ControlType3.Object,
		title: "Links",
		controls: {
			linksEnabled: {
				type: ControlType3.Boolean,
				title: "Enable",
				defaultValue: ParticleWrapper.defaultProps.linksOptions.linksEnabled,
			},
			linksColor: {
				type: ControlType3.Color,
				title: "Color",
				defaultValue: ParticleWrapper.defaultProps.linksOptions.linksColor,
				hidden: (props) => !props.linksEnabled,
			},
			linksOpacity: {
				type: ControlType3.Number,
				title: "Opacity",
				min: 0,
				max: 1,
				step: 0.1,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.linksOptions.linksOpacity,
				hidden: (props) => !props.linksEnabled,
			},
			linksDistance: {
				type: ControlType3.Number,
				title: "Distance",
				min: 0,
				max: 500,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.linksOptions.linksDistance,
				hidden: (props) => !props.linksEnabled,
			},
			linksWidth: {
				type: ControlType3.Number,
				title: "Width",
				min: 0,
				max: 10,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.linksOptions.linksWidth,
				hidden: (props) => !props.linksEnabled,
			},
		},
	},
	modeOptions: {
		type: ControlType3.Object,
		title: "Modes",
		controls: {
			connectDistance: {
				type: ControlType3.Number,
				title: "Connect",
				min: 0,
				max: 1e3,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.connectDistance,
			},
			connectRadius: {
				type: ControlType3.Number,
				title: "Connect Radius",
				min: 0,
				max: 1e3,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.connectRadius,
			},
			connectLinksOpacity: {
				type: ControlType3.Number,
				title: "Connect Links",
				min: 0,
				max: 1,
				step: 0.1,
				displayStepper: true,
				defaultValue:
					ParticleWrapper.defaultProps.modeOptions.connectLinksOpacity,
			},
			grabDistance: {
				type: ControlType3.Number,
				title: "Grab",
				min: 0,
				max: 1e3,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.grabDistance,
			},
			grabLinksOpacity: {
				type: ControlType3.Number,
				title: "Grab Links",
				min: 0,
				max: 1,
				step: 0.1,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.grabLinksOpacity,
			},
			bubbleDistance: {
				type: ControlType3.Number,
				title: "Bubble",
				min: 0,
				max: 1e3,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.bubbleDistance,
			},
			bubbleSize: {
				type: ControlType3.Number,
				title: "Bubble Size",
				min: 0,
				max: 1e3,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.bubbleSize,
			},
			bubbleDuration: {
				type: ControlType3.Number,
				title: "Bubble Duration",
				min: 0,
				max: 1,
				step: 0.1,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.bubbleDuration,
			},
			repulseDistance: {
				type: ControlType3.Number,
				title: "Repulse",
				min: 0,
				max: 1e3,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.repulseDistance,
			},
			repulseDuration: {
				type: ControlType3.Number,
				title: "Repulse Duration",
				min: 0,
				max: 10,
				step: 0.1,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.repulseDuration,
			},
			pushQuantity: {
				type: ControlType3.Number,
				title: "Push",
				min: 0,
				max: 100,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.pushQuantity,
			},
			removeQuantity: {
				type: ControlType3.Number,
				title: "Remove",
				min: 0,
				max: 100,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.removeQuantity,
			},
			trailQuantity: {
				type: ControlType3.Number,
				title: "Trail",
				min: 0,
				max: 100,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.trailQuantity,
			},
			trailDelay: {
				type: ControlType3.Number,
				title: "Trail Delay",
				min: 0,
				max: 10,
				step: 0.1,
				defaultValue: ParticleWrapper.defaultProps.modeOptions.trailDelay,
			},
		},
	},
	moveOptions: {
		type: ControlType3.Object,
		title: "Move",
		controls: {
			moveEnabled: {
				type: ControlType3.Boolean,
				title: "Enable",
				defaultValue: ParticleWrapper.defaultProps.moveOptions.moveEnabled,
			},
			moveDirection: {
				type: ControlType3.Enum,
				title: "Direction",
				options: [
					"none",
					"bottom",
					"left",
					"right",
					"top",
					"bottom-left",
					"bottom-right",
					"top-left",
					"top-right",
					"outside",
					"inside",
				],
				optionTitles: [
					"Random",
					"Bottom",
					"Left",
					"Right",
					"Top",
					"Bottom Left",
					"Bottom Right",
					"Top Left",
					"Top Right",
					"Outside",
					"Inside",
				],
				defaultValue: ParticleWrapper.defaultProps.moveOptions.moveDirection,
				hidden: (props) => !props.moveEnabled,
			},
			moveSpeed: {
				type: ControlType3.Number,
				title: "Speed",
				min: 0,
				max: 100,
				step: 0.1,
				defaultValue: ParticleWrapper.defaultProps.moveOptions.moveSpeed,
				hidden: (props) => !props.moveEnabled,
			},
			moveRandom: {
				type: ControlType3.Boolean,
				title: "Random",
				defaultValue: ParticleWrapper.defaultProps.moveOptions.moveRandom,
				hidden: (props) => !props.moveEnabled,
			},
			moveStraight: {
				type: ControlType3.Boolean,
				title: "Straight",
				defaultValue: ParticleWrapper.defaultProps.moveOptions.moveStraight,
				hidden: (props) => !props.moveEnabled,
			},
			moveOut: {
				type: ControlType3.Enum,
				title: "Out",
				options: [
					"none",
					"split",
					"bounce",
					"destroy",
					"out",
					"bounceHorizontal",
					"bounceVertical",
				],
				optionTitles: [
					"None",
					"Split",
					"Bounce",
					"Destroy",
					"Out",
					"Bounce Horizontal",
					"Bounce Vertical",
				],
				defaultValue: ParticleWrapper.defaultProps.moveOptions.moveOut,
				hidden: (props) => !props.moveEnabled,
			},
			moveVibrate: {
				type: ControlType3.Boolean,
				title: "Vibrate",
				defaultValue: ParticleWrapper.defaultProps.moveOptions.moveVibrate,
				hidden: (props) => !props.moveEnabled,
			},
			moveGravityEnabled: {
				type: ControlType3.Boolean,
				title: "Gravity",
				defaultValue:
					ParticleWrapper.defaultProps.moveOptions.moveGravityEnabled,
				hidden: (props) => !props.moveEnabled,
			},
			moveGravityAcceleration: {
				type: ControlType3.Number,
				title: "Gravity Acceleration",
				min: 0,
				max: 100,
				step: 0.1,
				defaultValue:
					ParticleWrapper.defaultProps.moveOptions.moveGravityAcceleration,
				hidden: (props) => !props.moveEnabled || !props.moveGravityEnabled,
			},
			moveGravityMaxSpeed: {
				type: ControlType3.Number,
				title: "Gravity Max Speed",
				min: 0,
				max: 100,
				step: 0.1,
				defaultValue:
					ParticleWrapper.defaultProps.moveOptions.moveGravityAcceleration,
				hidden: (props) => !props.moveEnabled || !props.moveGravityEnabled,
			},
			moveTrailEnabled: {
				type: ControlType3.Boolean,
				title: "Trail",
				defaultValue: ParticleWrapper.defaultProps.moveOptions.moveTrailEnabled,
				hidden: (props) => !props.moveEnabled,
			},
			moveTrailAmount: {
				type: ControlType3.Number,
				title: " ",
				min: 0,
				max: 1e3,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.moveOptions.moveTrailAmount,
				hidden: (props) => !props.moveEnabled || !props.moveTrailEnabled,
			},
			moveSpinEnabled: {
				type: ControlType3.Boolean,
				title: "Spin",
				defaultValue: ParticleWrapper.defaultProps.moveOptions.moveSpinEnabled,
				hidden: (props) => !props.moveEnabled,
			},
			moveSpinAcceleration: {
				type: ControlType3.Number,
				title: " ",
				min: 0,
				max: 1e3,
				step: 1,
				defaultValue:
					ParticleWrapper.defaultProps.moveOptions.moveSpinAcceleration,
				hidden: (props) => !props.moveEnabled || !props.moveSpinEnabled,
			},
			moveAttractEnabled: {
				type: ControlType3.Boolean,
				title: "Attract",
				defaultValue:
					ParticleWrapper.defaultProps.moveOptions.moveAttractEnabled,
				hidden: (props) => !props.moveEnabled,
			},
			moveAttractDistance: {
				type: ControlType3.Number,
				title: " ",
				min: 0,
				max: 1e3,
				step: 1,
				defaultValue:
					ParticleWrapper.defaultProps.moveOptions.moveAttractDistance,
				hidden: (props) => !props.moveEnabled || !props.moveAttractEnabled,
			},
		},
	},
	shapeOptions: {
		type: ControlType3.Object,
		title: "Shape",
		controls: {
			shapeType: {
				type: ControlType3.Enum,
				title: "Shape",
				options: [
					"circle",
					"edge",
					"triangle",
					"polygon",
					"star",
					"character",
					"image",
				],
				optionTitles: [
					"Circle",
					"Square",
					"Triangle",
					"Polygon",
					"Star",
					"Character",
					"Image",
				],
				defaultValue: ParticleWrapper.defaultProps.shapeOptions.characterType,
			},
			characterType: {
				type: ControlType3.String,
				title: "Character",
				defaultValue: ParticleWrapper.defaultProps.shapeOptions.characterType,
				hidden: (props) => props.shapeType !== "character",
			},
			imageSource: {
				type: ControlType3.Image,
				title: "Image",
				hidden: (props) => props.shapeType !== "image",
			},
			imageWidth: {
				type: ControlType3.Number,
				title: "Width",
				min: 0,
				max: 1e3,
				defaultValue: ParticleWrapper.defaultProps.shapeOptions.imageWidth,
				hidden: (props) => props.shapeType !== "image",
			},
			imageHeight: {
				type: ControlType3.Number,
				title: "Height",
				min: 0,
				max: 1e3,
				defaultValue: ParticleWrapper.defaultProps.shapeOptions.imageWidth,
				hidden: (props) => props.shapeType !== "image",
			},
		},
	},
	clickOptions: {
		type: ControlType3.Object,
		title: "Click",
		controls: {
			clickEnabled: {
				type: ControlType3.Boolean,
				title: "Enable",
				defaultValue: ParticleWrapper.defaultProps.clickOptions.clickEnabled,
			},
			clickModes: {
				type: ControlType3.Enum,
				title: "Mode",
				options: [
					"attract",
					"bubble",
					"push",
					"remove",
					"repulse",
					"pause",
					"trail",
				],
				optionTitles: [
					"Attract",
					"Bubble",
					"Push",
					"Remove",
					"Repulse",
					"Pause",
					"Trail",
				],
				defaultValue: ParticleWrapper.defaultProps.clickOptions.clickModes,
				hidden: (props) => !props.clickEnabled,
			},
		},
	},
	hoverOptions: {
		type: ControlType3.Object,
		title: "Hover",
		controls: {
			hoverEnabled: {
				type: ControlType3.Boolean,
				title: "Enable",
				defaultValue: ParticleWrapper.defaultProps.hoverOptions.hoverEnabled,
			},
			hoverModes: {
				type: ControlType3.Enum,
				title: "Mode",
				options: [
					"none",
					"attract",
					"bounce",
					"bubble",
					"connect",
					"grab",
					"light",
					"repulse",
					"slow",
					"trail",
				],
				optionTitles: [
					"None",
					"Attract",
					"Bounce",
					"Bubble",
					"Connect",
					"Grab",
					"Light",
					"Repulse",
					"Slow",
					"Trail",
				],
				defaultValue: ParticleWrapper.defaultProps.hoverOptions.hoverModes,
				hidden: (props) => !props.hoverEnabled,
			},
			hoverParallax: {
				type: ControlType3.Boolean,
				title: "Parallax",
				defaultValue: ParticleWrapper.defaultProps.hoverOptions.hoverParallax,
				hidden: (props) => !props.hoverEnabled,
			},
			hoverForce: {
				type: ControlType3.Number,
				min: 0,
				max: 50,
				step: 1,
				displayStepper: true,
				title: "Force",
				defaultValue: ParticleWrapper.defaultProps.hoverOptions.hoverForce,
				hidden: (props) => !props.hoverParallax || !props.hoverEnabled,
			},
			hoverSmooth: {
				type: ControlType3.Number,
				min: 0,
				max: 50,
				step: 1,
				displayStepper: true,
				title: "Smooth",
				defaultValue: ParticleWrapper.defaultProps.hoverOptions.hoverSmooth,
				hidden: (props) => !props.hoverParallax || !props.hoverEnabled,
			},
		},
	},
	rotateOptions: {
		type: ControlType3.Object,
		title: "Rotate",
		controls: {
			rotateValue: {
				type: ControlType3.Number,
				title: "Value",
				min: -360,
				max: 360,
				step: 1,
				displayStepper: true,
				defaultValue: ParticleWrapper.defaultProps.rotateOptions.rotateValue,
			},
			rotateDirection: {
				type: ControlType3.Enum,
				title: "Direction",
				options: ["clockwise", "counter-clockwise", "random"],
				optionTitles: ["Clockwise", "Counter Clockwise", "Random"],
				defaultValue:
					ParticleWrapper.defaultProps.rotateOptions.rotateDirection,
			},
			rotateAnimation: {
				type: ControlType3.Boolean,
				title: "Animate",
				defaultValue:
					ParticleWrapper.defaultProps.rotateOptions.rotateAnimation,
			},
			rotateSpeed: {
				type: ControlType3.Number,
				title: "Speed",
				min: 0,
				max: 100,
				step: 1,
				defaultValue: ParticleWrapper.defaultProps.rotateOptions.rotateSpeed,
				hidden: (props) => !props.rotateAnimation,
			},
			rotateSync: {
				type: ControlType3.Boolean,
				title: "Sync",
				defaultValue: ParticleWrapper.defaultProps.rotateOptions.rotateSync,
				hidden: (props) => !props.rotateAnimation,
			},
		},
	},
	radius: {
		type: ControlType3.Number,
		min: 0,
		max: 1e3,
		step: 1,
		displayStepper: true,
		defaultValue: ParticleWrapper.defaultProps.radius,
	},
	particlesID: {
		type: ControlType3.String,
		title: "ID",
		defaultValue: "One",
		placeholder: ParticleWrapper.defaultProps.particlesID,
	},
});
var makeHex = (property) => Color.toHexString(Color(property));

// /:https://framerusercontent.com/modules/Y0c19ostjQ6JrIrS9EpB/ZlMPPV0G0dewn2RXQ7S7/QDC8_m4BS.js
import { jsx as _jsx4 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls4,
	ControlType as ControlType4,
	cx as cx3,
	motion as motion3,
	useSVGTemplate as useSVGTemplate2,
	withCSS as withCSS3,
} from "unframer";
import * as React3 from "react";
import { forwardRef as forwardRef6 } from "react";
var Base2 = /* @__PURE__ */ forwardRef6(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG2 = motion3.create(Base2);
var SVG3 = /* @__PURE__ */ forwardRef6((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG2 {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG2>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg2 =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 9 C 0 4.029 4.029 0 9 0 C 13.971 0 18 4.029 18 9 C 18 13.971 13.971 18 9 18 C 4.029 18 0 13.971 0 9 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="18px" id="toDPs7Y9O" transform="translate(3 3)" width="18px"/><path d="M 0 9 C 0 4.029 4.029 0 9 0 C 13.971 0 18 4.029 18 9 C 18 13.971 13.971 18 9 18 C 4.029 18 0 13.971 0 9 Z" fill="transparent" height="18px" id="nB8qhy58t" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(3 3)" width="18px"/><path d="M 3.75 0 L 2.25 0 C 1.007 0 0 1.007 0 2.25 L 0 12.75" fill="transparent" height="12.75px" id="QFOnXWoYe" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(12 8.25)" width="3.75px"/><path d="M 0 0 L 6 0" fill="transparent" height="1px" id="rOK6Xhani" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(9 13.5)" width="6px"/></svg>';
var getProps3 = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps3(props);
	const href = useSVGTemplate2("1426455308", svg2);
	return (
		<SVG3
			{...restProps}
			className={cx3("framer-ojcNP", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG3>
	);
});
var css4 = [".framer-ojcNP { aspect-ratio: 1; display: block; width: 24px; }"];
var Icon3 = withCSS3(Component3, css4, "framer-ojcNP");
Icon3.displayName = "Facebook Logo";
var stdin_default5 = Icon3;
addPropertyControls4(Icon3, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType4.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType4.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType4.Number,
	},
});

// /:https://framerusercontent.com/modules/cuzxw3YvBzJq3sm0puns/eEMB6pzr9ouL7ZuuMEFc/HRa_2U6GS.js
import { jsx as _jsx5 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls5,
	ControlType as ControlType5,
	cx as cx4,
	Instance,
	Link,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS4,
} from "unframer";
import { LayoutGroup, motion as motion4, MotionConfigContext } from "unframer";
import * as React4 from "react";
import { useRef } from "react";
var enabledGestures = {
	EptH6fZjc: {
		hover: true,
	},
};
var serializationHash = "framer-3x6AT";
var variantClassNames = {
	EptH6fZjc: "framer-v-cmqdzy",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion4.create(React4.Fragment);
var getProps4 = ({ height, icon, id, link, width, ...props }) => {
	return {
		...props,
		RhBoiefR8: icon ?? props.RhBoiefR8 ?? stdin_default,
		YdTA2k7Lp: link ?? props.YdTA2k7Lp,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		RhBoiefR8,
		YdTA2k7Lp,
		...restProps
	} = getProps4(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "EptH6fZjc",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx4(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={YdTA2k7Lp}
						motionChild={true}
						nodeId={"EptH6fZjc"}
						openInNewTab={true}
						scopeId={"HRa_2U6GS"}
					>
						<motion4.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx4(scopingClassNames, "framer-cmqdzy", className2, classNames)} framer-fgygfz`}
							data-framer-name={"primary"}
							layoutDependency={layoutDependency}
							layoutId={"EptH6fZjc"}
							ref={refBinding}
							style={{
								borderBottomLeftRadius: 201,
								borderBottomRightRadius: 201,
								borderTopLeftRadius: 201,
								borderTopRightRadius: 201,
								...style,
							}}
							{...addPropertyOverrides(
								{
									"EptH6fZjc-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<Instance
								animated={true}
								className={"framer-zheq7"}
								Component={RhBoiefR8}
								layoutDependency={layoutDependency}
								layoutId={"MKWP5APPT"}
								style={{
									"--1m6trwb": 0,
									"--21h8s6":
										"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
									"--pgex8v": 1.5,
									opacity: 0.5,
								}}
								variants={{
									"EptH6fZjc-hover": {
										opacity: 1,
									},
								}}
							/>
						</motion4.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-3x6AT.framer-fgygfz, .framer-3x6AT .framer-fgygfz { display: block; }",
	".framer-3x6AT.framer-cmqdzy { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-3x6AT .framer-zheq7 { flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
];
var FramerHRa_2U6GS = withCSS4(Component4, css5, "framer-3x6AT");
var stdin_default6 = FramerHRa_2U6GS;
FramerHRa_2U6GS.displayName = "Elements/social media";
FramerHRa_2U6GS.defaultProps = {
	height: 40,
	width: 40,
};
addPropertyControls5(FramerHRa_2U6GS, {
	RhBoiefR8: {
		defaultValue: {
			identifier:
				"module:oMiuMYAdxzz5yk7pBqrm/FToqm3dwiHuJofBRASRI/Xx_sbLkzD.js:default",
			moduleId: "oMiuMYAdxzz5yk7pBqrm",
		},
		setModuleId: "omX0gWFPqDwhaiWwf6ab",
		title: "Icon",
		type: ControlType5.VectorSetItem,
	},
	YdTA2k7Lp: {
		title: "Link",
		type: ControlType5.Link,
	},
});
addFonts(
	FramerHRa_2U6GS,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/xoYBU8gDBmvqMMbrUyTD/HOx7zIeKjQptpSg8sjsx/ZjS3Yh4jr.js
var MotionDivWithFX = withFX(motion5.div);
var RichTextWithFX = withFX(RichText);
var MainButtonFonts = getFonts(stdin_default2);
var SmartComponentScopedContainerWithFX = withFX(SmartComponentScopedContainer);
var ElementsSocialMediaFonts = getFonts(stdin_default6);
var ParticlesFonts = getFonts(ParticleWrapper);
var serializationHash2 = "framer-DgMue";
var variantClassNames2 = {
	YEPxr4OSZ: "framer-v-563awg",
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 60,
};
var transition2 = {
	damping: 60,
	delay: 0.3,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var transition3 = {
	damping: 60,
	delay: 0.4,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var transition4 = {
	damping: 60,
	delay: 0.5,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var transition5 = {
	damping: 60,
	delay: 0.6,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React5.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React5.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion5.create(React5.Fragment);
var getProps5 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component5 = /* @__PURE__ */ React5.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React5.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps5(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "YEPxr4OSZ",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx5(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion5.section
						{...restProps}
						{...gestureHandlers}
						className={cx5(
							scopingClassNames,
							"framer-563awg",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"YEPxr4OSZ"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(0, 0, 0))",
							...style,
						}}
					>
						<motion5.div
							className={"framer-na8crx"}
							data-framer-name={"container"}
							layoutDependency={layoutDependency}
							layoutId={"oZe0iJedP"}
						>
							<motion5.div
								className={"framer-1tfyokq"}
								data-framer-name={"text"}
								layoutDependency={layoutDependency}
								layoutId={"Oyd5syg3c"}
							>
								<MotionDivWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-bx9d63"}
									data-framer-name={"tag"}
									layoutDependency={layoutDependency}
									layoutId={"Ny9OOo5V9"}
									style={{
										borderBottomLeftRadius: 123,
										borderBottomRightRadius: 123,
										borderTopLeftRadius: 123,
										borderTopRightRadius: 123,
									}}
								>
									<motion5.div
										className={"framer-17of0ra"}
										data-framer-name={"line"}
										layoutDependency={layoutDependency}
										layoutId={"adjzL6dSZ"}
										style={{
											background:
												"linear-gradient(90deg, var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(0, 0, 0)) 0%, var(--token-a85af9cb-7834-4006-a277-2dd1295ae376, rgb(255, 255, 255)) 100%)",
											opacity: 0.5,
										}}
									/>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1eq4mtq"}
										fonts={["Inter", "Inter-Italic"]}
										layoutDependency={layoutDependency}
										layoutId={"G6Ies2OOv"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React5.Fragment>
											<motion5.p
												className={"framer-styles-preset-1kvyxmc"}
												data-styles-preset={"n7RLEGRKm"}
											>
												<motion5.em>{"Reach out anytime"}</motion5.em>
											</motion5.p>
										</React5.Fragment>
									</RichText>
									<motion5.div
										className={"framer-ybb2xf"}
										data-framer-name={"line"}
										layoutDependency={layoutDependency}
										layoutId={"atPT02oHJ"}
										style={{
											background:
												"linear-gradient(270deg, var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(0, 0, 0)) 0%, var(--token-a85af9cb-7834-4006-a277-2dd1295ae376, rgb(255, 255, 255)) 100%)",
											opacity: 0.5,
										}}
									/>
								</MotionDivWithFX>
								<RichTextWithFX
									__framer__animate={{
										transition: transition3,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-1yfk68t"}
									data-framer-name={"Let\u2019s Stay Connected"}
									fonts={["Inter-Medium", "GF;Instrument Serif-italic"]}
									layoutDependency={layoutDependency}
									layoutId={"caHbjDyDn"}
									style={{
										"--extracted-1of0zx5":
											"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React5.Fragment>
										<motion5.h2
											style={{
												"--font-selector": "SW50ZXItTWVkaXVt",
												"--framer-font-size": "44px",
												"--framer-font-weight": "500",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-1of0zx5, var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230)))",
											}}
										>
											<motion5.span
												data-text-fill={"true"}
												style={{
													backgroundImage:
														"linear-gradient(161deg, var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230)) 51.657657657657666%, var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13)) 166%)",
												}}
											>
												{"Ready to Automate Smarter? Let\u2019s "}
												<motion5.span
													style={{
														"--font-selector":
															"R0Y7SW5zdHJ1bWVudCBTZXJpZi1pdGFsaWM=",
														"--framer-font-family":
															'"Instrument Serif", "Instrument Serif Placeholder", serif',
														"--framer-font-style": "italic",
														"--framer-font-weight": "400",
													}}
												>
													{"Build Together"}
												</motion5.span>
											</motion5.span>
										</motion5.h2>
									</React5.Fragment>
								</RichTextWithFX>
								<RichTextWithFX
									__framer__animate={{
										transition: transition4,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__fromCanvasComponent={true}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-304br6"}
									data-framer-name={
										"Stay Updated on our future resources and course releases etc.."
									}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"sMNFiaqaM"}
									style={{
										"--framer-paragraph-spacing": "0px",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React5.Fragment>
										<motion5.p
											className={"framer-styles-preset-1kvyxmc"}
											data-styles-preset={"n7RLEGRKm"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{"Schedule a Call and Begin Automating"}
										</motion5.p>
									</React5.Fragment>
								</RichTextWithFX>
							</motion5.div>
							<ComponentViewportProvider
								height={50}
								y={
									(componentViewport?.y || 0) +
									100 +
									(((componentViewport?.height || 200) - 200 - 528.4) / 2 +
										0 +
										0) +
									0 +
									262.4
								}
							>
								<SmartComponentScopedContainerWithFX
									__framer__animate={{
										transition: transition4,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-114gvbn-container"}
									layoutDependency={layoutDependency}
									layoutId={"ghNhj46c0-container"}
									nodeId={"ghNhj46c0"}
									rendersWithMotion={true}
									scopeId={"ZjS3Yh4jr"}
								>
									{_jsx6(stdin_default2, {
										D_lQwlRhv: stdin_default3,
										height: "100%",
										id: "ghNhj46c0",
										layoutId: "ghNhj46c0",
										pkd7Pcy3s: true,
										variant: "u8HXU5hd9",
										width: "100%",
										WygjbYACO: "Book A Free Call",
										ypOX2jdFN: "https://framer.link/D4dc7gs",
									})}
								</SmartComponentScopedContainerWithFX>
							</ComponentViewportProvider>
							<MotionDivWithFX
								__framer__animate={{
									transition: transition5,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-12qc9gc"}
								data-framer-name={"social links"}
								layoutDependency={layoutDependency}
								layoutId={"wGtEpE3DL"}
							>
								<ComponentViewportProvider
									height={40}
									y={
										(componentViewport?.y || 0) +
										100 +
										(((componentViewport?.height || 200) - 200 - 528.4) / 2 +
											0 +
											0) +
										0 +
										336.4 +
										0
									}
								>
									<SmartComponentScopedContainer
										className={"framer-aut5hj-container"}
										layoutDependency={layoutDependency}
										layoutId={"l7IesM4Ei-container"}
										nodeId={"l7IesM4Ei"}
										rendersWithMotion={true}
										scopeId={"ZjS3Yh4jr"}
									>
										{_jsx6(stdin_default6, {
											height: "100%",
											id: "l7IesM4Ei",
											layoutId: "l7IesM4Ei",
											RhBoiefR8: stdin_default,
											width: "100%",
											YdTA2k7Lp: "https://x.com/home",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<motion5.div
									className={"framer-1mho8uy"}
									data-framer-name={"separation"}
									layoutDependency={layoutDependency}
									layoutId={"xS92ZBtDL"}
									style={{
										backgroundColor:
											"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(255, 255, 255, 0.07))",
									}}
								/>
								<ComponentViewportProvider
									height={40}
									y={
										(componentViewport?.y || 0) +
										100 +
										(((componentViewport?.height || 200) - 200 - 528.4) / 2 +
											0 +
											0) +
										0 +
										336.4 +
										0
									}
								>
									<SmartComponentScopedContainer
										className={"framer-1y1od3v-container"}
										layoutDependency={layoutDependency}
										layoutId={"ai768V2qI-container"}
										nodeId={"ai768V2qI"}
										rendersWithMotion={true}
										scopeId={"ZjS3Yh4jr"}
									>
										{_jsx6(stdin_default6, {
											height: "100%",
											id: "ai768V2qI",
											layoutId: "ai768V2qI",
											RhBoiefR8: stdin_default4,
											width: "100%",
											YdTA2k7Lp: "https://www.instagram.com/",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<motion5.div
									className={"framer-1366z1o"}
									data-framer-name={"separation"}
									layoutDependency={layoutDependency}
									layoutId={"GOzzziSR3"}
									style={{
										backgroundColor:
											"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(255, 255, 255, 0.07))",
									}}
								/>
								<ComponentViewportProvider
									height={40}
									y={
										(componentViewport?.y || 0) +
										100 +
										(((componentViewport?.height || 200) - 200 - 528.4) / 2 +
											0 +
											0) +
										0 +
										336.4 +
										0
									}
								>
									<SmartComponentScopedContainer
										className={"framer-1y9ebuj-container"}
										layoutDependency={layoutDependency}
										layoutId={"LsIHLVsPm-container"}
										nodeId={"LsIHLVsPm"}
										rendersWithMotion={true}
										scopeId={"ZjS3Yh4jr"}
									>
										{_jsx6(stdin_default6, {
											height: "100%",
											id: "LsIHLVsPm",
											layoutId: "LsIHLVsPm",
											RhBoiefR8: stdin_default5,
											width: "100%",
											YdTA2k7Lp: "https://www.facebook.com/",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</MotionDivWithFX>
							<RichTextWithFX
								__framer__animate={{
									transition: transition5,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1xyj674"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"EhbieRt6Z"}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React5.Fragment>
									<motion5.p
										className={"framer-styles-preset-1kvyxmc"}
										data-styles-preset={"n7RLEGRKm"}
										style={{
											"--framer-text-alignment": "center",
										}}
									>
										{"landio@support.com"}
									</motion5.p>
								</React5.Fragment>
							</RichTextWithFX>
						</motion5.div>
						<motion5.div
							className={"framer-muv2ly"}
							data-framer-name={"border"}
							layoutDependency={layoutDependency}
							layoutId={"IkZ3QpWWB"}
							style={{
								background:
									"radial-gradient(50% 50% at 50% 50%, var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(255, 255, 255, 0.07)) 0%, var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(0, 0, 0)) 100%)",
							}}
						/>
						<motion5.div
							className={"framer-bj356y"}
							data-framer-name={"bg shape"}
							layoutDependency={layoutDependency}
							layoutId={"vfW9xOMhK"}
							style={{
								background:
									"radial-gradient(50% 50% at 50% 50%, var(--token-98e77689-c0ed-4bec-a0a3-e86d11b001fb, rgba(213, 219, 230, 0.7)) 0%, rgba(4, 7, 13, 0) 100%)",
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
								opacity: 0.1,
								rotate: -13,
							}}
						/>
						<ComponentViewportProvider>
							<SmartComponentScopedContainer
								className={"framer-1jsk3oz-container"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"qSG63vaLy-container"}
								nodeId={"qSG63vaLy"}
								rendersWithMotion={true}
								scopeId={"ZjS3Yh4jr"}
								style={{
									mask: "radial-gradient(40% 46% at 50.9% 89.5%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0.8) 36.8823902027027%, rgba(0, 0, 0, 0) 100%) add",
									WebkitMask:
										"radial-gradient(40% 46% at 50.9% 89.5%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0.8) 36.8823902027027%, rgba(0, 0, 0, 0) 100%) add",
								}}
							>
								<ParticleWrapper
									background={"rgba(0, 0, 0, 0)"}
									clickOptions={{
										clickEnabled: false,
										clickModes: "push",
									}}
									color={"rgba(194, 196, 204, 0.9)"}
									colors={[]}
									densityOptions={{
										densityArea: 2194,
										densityEnable: false,
										densityFactor: 100,
									}}
									fpsOptions={60}
									height={"100%"}
									hoverOptions={{
										hoverEnabled: true,
										hoverForce: 40,
										hoverModes: "none",
										hoverParallax: true,
										hoverSmooth: 30,
									}}
									id={"qSG63vaLy"}
									layoutId={"qSG63vaLy"}
									linksOptions={{
										linksColor: "rgb(255, 255, 255)",
										linksDistance: 100,
										linksEnabled: false,
										linksOpacity: 0.2,
										linksWidth: 1,
									}}
									modeOptions={{
										bubbleDistance: 100,
										bubbleDuration: 0.4,
										bubbleSize: 40,
										connectDistance: 100,
										connectLinksOpacity: 0.2,
										connectRadius: 50,
										grabDistance: 100,
										grabLinksOpacity: 0.2,
										pushQuantity: 4,
										removeQuantity: 4,
										repulseDistance: 200,
										repulseDuration: 1.2,
										trailDelay: 0.1,
										trailQuantity: 10,
									}}
									moveOptions={{
										moveAttractDistance: 100,
										moveAttractEnabled: false,
										moveDirection: "none",
										moveEnabled: true,
										moveGravityAcceleration: 1,
										moveGravityEnabled: false,
										moveGravityMaxSpeed: 2,
										moveOut: "out",
										moveRandom: false,
										moveSpeed: 1,
										moveSpinAcceleration: 1,
										moveSpinEnabled: false,
										moveStraight: false,
										moveTrailAmount: 100,
										moveTrailEnabled: false,
										moveVibrate: false,
									}}
									number={50}
									opacityOptions={{
										opacity: 1,
										opacityMax: 1,
										opacityMin: 0.8,
										opacityType: false,
									}}
									particlesID={"two"}
									radius={0}
									rotateOptions={{
										rotateAnimation: false,
										rotateDirection: "random",
										rotateSpeed: 5,
										rotateSync: false,
										rotateValue: 0,
									}}
									shapeOptions={{
										characterType: "\u2728",
										imageHeight: 100,
										imageWidth: 100,
										shapeType: "circle",
									}}
									sizeOptions={{
										size: 1.5,
										sizeMax: 1,
										sizeMin: 0.5,
										sizeType: false,
									}}
									style={{
										height: "100%",
										width: "100%",
									}}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion5.section>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-DgMue.framer-telchp, .framer-DgMue .framer-telchp { display: block; }",
	".framer-DgMue.framer-563awg { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 100px 40px 100px 40px; position: relative; width: 1200px; }",
	".framer-DgMue .framer-na8crx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 1240px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 3; }",
	".framer-DgMue .framer-1tfyokq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; max-width: 613px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-DgMue .framer-bx9d63 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 24px 0px 24px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-DgMue .framer-17of0ra, .framer-DgMue .framer-ybb2xf { flex: none; height: 1px; overflow: hidden; position: relative; width: 69px; }",
	".framer-DgMue .framer-1eq4mtq { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-DgMue .framer-1yfk68t, .framer-DgMue .framer-1xyj674 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-DgMue .framer-304br6 { flex: none; height: auto; max-width: 75%; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-DgMue .framer-114gvbn-container, .framer-DgMue .framer-aut5hj-container, .framer-DgMue .framer-1y1od3v-container, .framer-DgMue .framer-1y9ebuj-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-DgMue .framer-12qc9gc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-DgMue .framer-1mho8uy, .framer-DgMue .framer-1366z1o { flex: none; height: 24px; overflow: hidden; position: relative; width: 2px; }",
	".framer-DgMue .framer-muv2ly { bottom: 0px; flex: none; height: 4px; left: 0px; position: absolute; right: 0px; z-index: 1; }",
	".framer-DgMue .framer-bj356y { bottom: -249px; flex: none; height: 499px; left: calc(50.00000000000002% - 793px / 2); pointer-events: none; position: absolute; width: 793px; z-index: 4; }",
	".framer-DgMue .framer-1jsk3oz-container { bottom: 0px; flex: none; height: 642px; left: 0px; pointer-events: none; position: absolute; right: 0px; z-index: 3; }",
	...css,
];
var FramerZjS3Yh4jr = withCSS5(Component5, css6, "framer-DgMue");
var stdin_default7 = FramerZjS3Yh4jr;
FramerZjS3Yh4jr.displayName = "CTA section";
FramerZjS3Yh4jr.defaultProps = {
	height: 577,
	width: 1200,
};
addFonts2(
	FramerZjS3Yh4jr,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "italic",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Instrument Serif",
					source: "google",
					style: "italic",
					uiFamilyName: "Instrument Serif",
					url: "https://fonts.gstatic.com/s/instrumentserif/v5/jizHRFtNs2ka5fXjeivQ4LroWlx-6zATjnTNgNq55w.woff2",
					weight: "400",
				},
			],
		},
		...MainButtonFonts,
		...ElementsSocialMediaFonts,
		...ParticlesFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cta-section
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e6ca028d8dcade9bd82279484f423380160c521ae9704eaaee26e5448359232b"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default7, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaSectionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e6ca028d8dcade9bd82279484f423380160c521ae9704eaaee26e5448359232b"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default7}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default7);
var cta_section_default = ComponentWithRoot;
export { cta_section_default as default };
