// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e6ca028d8dcade9b "landio (copy)", do not edit manually */
"use client";

import { stdin_default } from "./chunks/chunk-BRAIHAZ6.js";
import "./chunks/chunk-7ASBMXIN.js";
import "./chunks/chunk-4NPMLM6U.js";
import { routes } from "./chunks/chunk-RDBOTDVL.js";
import "./styles.css";

// virtual:navigation/footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/DhR8M10e9H1ZuleZFXnj/JulpmihGdd00XmRplVg3/XFu5Bv2b3.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var FooterFonts = getFonts(stdin_default);
var serializationHash = "framer-P37M0";
var variantClassNames = {
	d6oAjwfGi: "framer-v-9uevgp",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "d6oAjwfGi",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.footer
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-9uevgp",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"d6oAjwfGi"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider
							height={208}
							width={`calc(${componentViewport?.width || "100vw"} - 120px)`}
							y={
								(componentViewport?.y || 0) +
								60 +
								(((componentViewport?.height || 328) - 120 - 208) / 2 + 0 + 0)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1mw9dd5-container"}
								layoutDependency={layoutDependency}
								layoutId={"XcJG98O_b-container"}
								nodeId={"XcJG98O_b"}
								rendersWithMotion={true}
								scopeId={"XFu5Bv2b3"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "XcJG98O_b",
									layoutId: "XcJG98O_b",
									style: {
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-P37M0.framer-12a7vn2, .framer-P37M0 .framer-12a7vn2 { display: block; }",
	".framer-P37M0.framer-9uevgp { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: min-content; justify-content: center; overflow: visible; padding: 60px; position: relative; width: 1200px; }",
	".framer-P37M0 .framer-1mw9dd5-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var FramerXFu5Bv2b3 = withCSS(Component, css, "framer-P37M0");
var stdin_default2 = FramerXFu5Bv2b3;
FramerXFu5Bv2b3.displayName = "Navigation/Footer";
FramerXFu5Bv2b3.defaultProps = {
	height: 328,
	width: 1200,
};
addFonts(
	FramerXFu5Bv2b3,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...FooterFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation/footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e6ca028d8dcade9bd82279484f423380160c521ae9704eaaee26e5448359232b"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e6ca028d8dcade9bd82279484f423380160c521ae9704eaaee26e5448359232b"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_default = ComponentWithRoot;
export { footer_default as default };
