// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e6ca028d8dcade9b "landio (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * logo?: {src: string, srcSet?: string, alt?: string} // logo
}} Props

 */
import { routes } from "./chunks/chunk-RDBOTDVL.js";

// virtual:logo-box
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/67c835RBLLMfYlIS8WSN/B9jwD4FNeK6IzA642x0u/NiUV28iph.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-2Oiu6";
var variantClassNames = {
	X3TFFHCCO: "framer-v-1kwgrva",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
			src: value,
		}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, logo, width, ...props }) => {
	return {
		...props,
		qBkMUnNuR: logo ??
			props.qBkMUnNuR ?? {
			alt: "",
			src: "/tradepilot-01.svg",
		},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, qBkMUnNuR, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "X3TFFHCCO",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1kwgrva",
							className,
							classNames,
						)}
						data-framer-name={"primary"}
						layoutDependency={layoutDependency}
						layoutId={"X3TFFHCCO"}
						ref={ref ?? ref1}
						style={{
							backgroundColor:
								"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(11, 14, 24))",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							boxShadow:
								"0px 0.7065919983928324px 0.7065919983928324px -0.6666666666666666px rgba(64, 120, 168, 0.36936), 0px 1.8065619053231785px 1.8065619053231785px -1.3333333333333333px rgba(64, 120, 168, 0.35902), 0px 3.6217592146567767px 3.6217592146567767px -2px rgba(64, 120, 168, 0.34196), 0px 6.8655999097303715px 6.8655999097303715px -2.6666666666666665px rgba(64, 120, 168, 0.31146), 0px 13.646761411524492px 13.646761411524492px -3.3333333333333335px rgba(64, 120, 168, 0.24772), 0px 30px 30px -4px rgba(64, 120, 168, 0.094)",
							...style,
						}}
					>
						<motion.div
							className={"framer-1j6fkt8"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"LPJVWw2rC"}
							style={{
								backgroundColor:
									"var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(11, 14, 24))",
								borderBottomLeftRadius: 10,
								borderBottomRightRadius: 10,
								borderTopLeftRadius: 10,
								borderTopRightRadius: 10,
								boxShadow:
									"0px 0.7961918735236395px 0.7961918735236395px -0.875px rgba(87, 133, 179, 0.47885), 0px 2.414506143104518px 2.414506143104518px -1.75px rgba(87, 133, 179, 0.4562), 0px 6.382653521484461px 6.382653521484461px -2.625px rgba(87, 133, 179, 0.40064), 0px 20px 20px -3.5px rgba(87, 133, 179, 0.21)",
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fit",
									intrinsicHeight: 40,
									intrinsicWidth: 44,
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
										(10 +
											((componentViewport?.height || 96) -
												20 -
												((componentViewport?.height || 96) - 20) * 1) /
											2) +
										(16 +
											(((componentViewport?.height || 96) - 20) * 1 -
												32 -
												(((componentViewport?.height || 96) - 20) * 1 - 32) *
												1) /
											2),
									),
									pixelHeight: 74,
									pixelWidth: 74,
									sizes: `max(max(${componentViewport?.width || "100vw"} - 20px, 1px) - 32px, 1px)`,
									...toResponsiveImage(qBkMUnNuR),
									...{
										positionX: "center",
										positionY: "center",
									},
								}}
								className={"framer-qtoqks"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"lto6vAFIN"}
								style={{
									rotate: 90,
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-2Oiu6.framer-1f77nla, .framer-2Oiu6 .framer-1f77nla { display: block; }",
	".framer-2Oiu6.framer-1kwgrva { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 96px; justify-content: center; overflow: visible; padding: 10px; position: relative; width: 96px; }",
	".framer-2Oiu6 .framer-1j6fkt8 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; overflow: visible; padding: 16px; position: relative; width: 1px; }",
	".framer-2Oiu6 .framer-qtoqks { flex: 1 0 0px; height: 100%; overflow: visible; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-2Oiu6.framer-1kwgrva, .framer-2Oiu6 .framer-1j6fkt8 { gap: 0px; } .framer-2Oiu6.framer-1kwgrva > *, .framer-2Oiu6 .framer-1j6fkt8 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-2Oiu6.framer-1kwgrva > :first-child, .framer-2Oiu6 .framer-1j6fkt8 > :first-child { margin-left: 0px; } .framer-2Oiu6.framer-1kwgrva > :last-child, .framer-2Oiu6 .framer-1j6fkt8 > :last-child { margin-right: 0px; } }",
];
var FramerNiUV28iph = withCSS(Component, css, "framer-2Oiu6");
var stdin_default = FramerNiUV28iph;
FramerNiUV28iph.displayName = "Logo box";
FramerNiUV28iph.defaultProps = {
	height: 96,
	width: 96,
};
addPropertyControls(FramerNiUV28iph, {
	qBkMUnNuR: {
		__defaultAssetReference:
			"data:framer/asset-reference,5BVUI56YoqDFZ1xvzbir5lf9sZA.svg?originalFilename=Icon.svg&preferredSize=auto",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,5BVUI56YoqDFZ1xvzbir5lf9sZA.svg?originalFilename=Icon.svg&preferredSize=auto",
		},
		title: "logo",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramerNiUV28iph,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:logo-box
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e6ca028d8dcade9bd82279484f423380160c521ae9704eaaee26e5448359232b"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LogoBoxFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e6ca028d8dcade9bd82279484f423380160c521ae9704eaaee26e5448359232b"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var logo_box_default = ComponentWithRoot;
export { logo_box_default as default };
