// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e6ca028d8dcade9b "landio (copy)", do not edit manually */
"use client";
import "./styles.css";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import {
	className,
	className2,
	css,
	css2,
	fonts,
	fonts2,
	stdin_default2 as stdin_default,
} from "./chunks/chunk-GUQRTOGD.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-5PPLI45H.js";
import { routes } from "./chunks/chunk-RDBOTDVL.js";

// virtual:smart-process
import { Fragment as Fragment4 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/WGx9YFtUrCsxprs6fne5/rlWAijSNN5LdY0P67X6K/m7MVr9wQx.js
import { jsx as _jsx4, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts3,
	ComponentViewportProvider as ComponentViewportProvider2,
	cx as cx4,
	getFonts as getFonts2,
	getFontsFromSharedStyle as getFontsFromSharedStyle3,
	RichText as RichText3,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useComponentViewport as useComponentViewport3,
	useLocaleInfo as useLocaleInfo3,
	useVariantState as useVariantState3,
	withCSS as withCSS4,
	withFX as withFX2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup3,
	motion as motion4,
	MotionConfigContext as MotionConfigContext3,
} from "unframer";
import * as React4 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/ZWll1fJWgbCHlCe3KGMT/QZog7BJ01M2gn09ToPno/C3_KUgzte.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 14.25 13.5 L 0 13.5 L 0 9 L 5.25 9 L 5.25 4.5 L 10.5 4.5 L 10.5 0 L 15.75 0 L 15.75 12 C 15.75 12.828 15.078 13.5 14.25 13.5 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="13.5px" id="OS5KcxGyH" transform="translate(6.75 5.25)" width="15.75px"/><path d="M 0 13.5 L 5.25 13.5 L 5.25 9 L 10.5 9 L 10.5 4.5 L 15.75 4.5 L 15.75 0 L 21 0" fill="transparent" height="13.5px" id="UAaSNmiRO" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(1.5 5.25)" width="21px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className6,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("3233394945", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-szLWP", className6)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css4 = [".framer-szLWP { aspect-ratio: 1; display: block; width: 24px; }"];
var Icon = withCSS(Component, css4, "framer-szLWP");
Icon.displayName = "Steps";
var stdin_default2 = Icon;
addPropertyControls(Icon, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/i4oYUrV1raV2sMIw30R1/ddo0wqN8ZPwy5wEVUtbM/OLoUGThIY.js
import { jsx as _jsx3, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx as cx3,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	Image,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useOnVariantChange,
	useVariantState as useVariantState2,
	withCSS as withCSS3,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion3,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React3 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/aZEGzBDbOQXEq0mfVMoD/u08s2ABUiQubP1gSsNLI/nf0yFfa08.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"Inter",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css5 = [
	'.framer-dxQZK .framer-styles-preset-qbxcjn:not(.rich-text-wrapper), .framer-dxQZK .framer-styles-preset-qbxcjn.rich-text-wrapper p { --framer-font-family: "Inter", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.01em; --framer-line-height: 30px; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, #d5dbe6); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className4 = "framer-dxQZK";

// /:https://framerusercontent.com/modules/jZSyrqJEpEcvHQW8cddZ/dkjHRd4GlUw4Wqkep1Kq/rmSf_ipOK.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;Inter-regular",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts5 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/inter/v19/UcCO3FwrK3iLTeHuS_nVMrMxCp50SjIw2boKoduKmMEVuLyfMZ1rib2Bg-4.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css6 = [
	'.framer-giQQa .framer-styles-preset-17f5k4v:not(.rich-text-wrapper), .framer-giQQa .framer-styles-preset-17f5k4v.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-98e77689-c0ed-4bec-a0a3-e86d11b001fb, rgba(213, 219, 230, 0.7)); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-giQQa .framer-styles-preset-17f5k4v:not(.rich-text-wrapper), .framer-giQQa .framer-styles-preset-17f5k4v.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-98e77689-c0ed-4bec-a0a3-e86d11b001fb, rgba(213, 219, 230, 0.7)); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-giQQa .framer-styles-preset-17f5k4v:not(.rich-text-wrapper), .framer-giQQa .framer-styles-preset-17f5k4v.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.02em; --framer-line-height: 1.6em; --framer-paragraph-spacing: 20px; --framer-text-alignment: left; --framer-text-color: var(--token-98e77689-c0ed-4bec-a0a3-e86d11b001fb, rgba(213, 219, 230, 0.7)); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }',
];
var className5 = "framer-giQQa";

// /:https://framerusercontent.com/modules/yLCzivIw9MsT84KCVEVw/PlXyiib5yJj1K87g0U0C/kp3q5qt1W.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";
var enabledGestures = {
	b88z41vz_: {
		hover: true,
	},
};
var cycleOrder = ["rObxpNGp_", "zNzyWdzz3", "b88z41vz_"];
var serializationHash = "framer-dg50c";
var variantClassNames = {
	b88z41vz_: "framer-v-stukul",
	rObxpNGp_: "framer-v-409wy3",
	zNzyWdzz3: "framer-v-prt7qe",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	Complete: "zNzyWdzz3",
	Inactive: "b88z41vz_",
	Playing: "rObxpNGp_",
};
var getProps2 = ({ click, height, id, title, width, ...props }) => {
	return {
		...props,
		dDnGYdLN4: title ?? props.dDnGYdLN4 ?? "STEP 1",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "rObxpNGp_",
		vYMcHT6Mz: click ?? props.vYMcHT6Mz,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		dDnGYdLN4,
		vYMcHT6Mz,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "rObxpNGp_",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1k1ht34 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (vYMcHT6Mz) {
			const res = await vYMcHT6Mz(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className2];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-409wy3",
							"glass-4 hover:glass-5 shadow-md relative overflow-hidden rounded-md transition-all",
							className6,
							classNames,
						)}
						data-framer-name={"Playing"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"rObxpNGp_"}
						onTap={onTap1k1ht34}
						ref={refBinding}
						style={{
							backgroundColor: "transparent",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							boxShadow: "none",
							...style,
						}}
						variants={{
							"b88z41vz_-hover": {
								backgroundColor: "transparent",
							},
						}}
						{...addPropertyOverrides(
							{
								"b88z41vz_-hover": {
									"data-framer-name": void 0,
								},
								b88z41vz_: {
									"data-framer-name": "Inactive",
								},
								zNzyWdzz3: {
									"data-framer-name": "Complete",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1gekb2v"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"X7vL8UOYi"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={dDnGYdLN4}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React2.Fragment>
								<motion2.p
									className={"framer-styles-preset-1u349i7"}
									data-styles-preset={"rerWrmQ65"}
								>
									{"STEP 1"}
								</motion2.p>
							</React2.Fragment>
						</RichText>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-dg50c.framer-19oxzmg, .framer-dg50c .framer-19oxzmg { display: block; }",
	".framer-dg50c.framer-409wy3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 44px; justify-content: center; overflow: hidden; padding: 13px; position: relative; width: 134px; will-change: var(--framer-will-change-override, transform); }",
	".framer-dg50c .framer-1gekb2v { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css2,
];
var Framerkp3q5qt1W = withCSS2(Component2, css7, "framer-dg50c");
var stdin_default3 = Framerkp3q5qt1W;
Framerkp3q5qt1W.displayName = "Component / Step";
Framerkp3q5qt1W.defaultProps = {
	height: 44,
	width: 134,
};
addPropertyControls2(Framerkp3q5qt1W, {
	variant: {
		options: ["rObxpNGp_", "zNzyWdzz3", "b88z41vz_"],
		optionTitles: ["Playing", "Complete", "Inactive"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	dDnGYdLN4: {
		defaultValue: "STEP 1",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
	vYMcHT6Mz: {
		title: "Click",
		type: ControlType2.EventHandler,
	},
});
addFonts(
	Framerkp3q5qt1W,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/i4oYUrV1raV2sMIw30R1/ddo0wqN8ZPwy5wEVUtbM/OLoUGThIY.js
var ComponentStepFonts = getFonts(stdin_default3);
var ImageWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(Image),
);
var cycleOrder2 = ["qm6JrJUbt", "IjbyRy7KQ", "gsmeDGDZU", "NzJeMoZQz"];
var serializationHash2 = "framer-IlZB5";
var variantClassNames2 = {
	gsmeDGDZU: "framer-v-etuyv8",
	IjbyRy7KQ: "framer-v-t16tf9",
	NzJeMoZQz: "framer-v-rvsbxq",
	qm6JrJUbt: "framer-v-6xxbrk",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	delay: 0,
	duration: 0.3,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var transition2 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
			src: value,
		}
		: void 0;
};
var transition3 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.6,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition4 = {
	damping: 100,
	delay: 0.05,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var textEffect = {
	effect: animation2,
	repeat: false,
	startDelay: 0.2,
	threshold: 0,
	tokenization: "word",
	transition: transition4,
	trigger: "onInView",
	type: "appear",
};
var transition5 = {
	damping: 100,
	delay: 0.01,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var textEffect1 = {
	effect: animation2,
	repeat: false,
	startDelay: 0.3,
	threshold: 0,
	tokenization: "word",
	transition: transition5,
	trigger: "onInView",
	type: "appear",
};
var Transition2 = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion3.create(React3.Fragment);
var humanReadableEnumMap = {
	Horizontal: "row",
	Vertical: "column",
};
var humanReadableVariantMap2 = {
	"Step 1": "qm6JrJUbt",
	"Step 2": "IjbyRy7KQ",
	"Step 3": "gsmeDGDZU",
	"Transition to 1 (Don't Change Content Here)": "NzJeMoZQz",
};
var getProps3 = ({
	direction3,
	height,
	id,
	imagesVisible,
	step1Discription,
	step1Heading,
	step1Img,
	step2Discription,
	step2Heading,
	step2Img,
	step3Discription,
	step3Heading,
	step3Img,
	width,
	...props
}) => {
	return {
		...props,
		A3R33WBVq: imagesVisible ?? props.A3R33WBVq ?? true,
		CtHiBo6zh: step3Img ??
			props.CtHiBo6zh ?? {
			pixelHeight: 1012,
			pixelWidth: 1536,
			src: "https://framerusercontent.com/images/0DBAix0ysUgnw6WhKOms5oGcN8.png?scale-down-to=1024",
			srcSet:
				"https://framerusercontent.com/images/0DBAix0ysUgnw6WhKOms5oGcN8.png?scale-down-to=512 512w,https://framerusercontent.com/images/0DBAix0ysUgnw6WhKOms5oGcN8.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/0DBAix0ysUgnw6WhKOms5oGcN8.png 1536w",
		},
		ffy1TjphS:
			humanReadableEnumMap[direction3] ??
			direction3 ??
			props.ffy1TjphS ??
			"row",
		Gp0XQ20hc:
			step3Discription ??
			props.Gp0XQ20hc ??
			"Connect your broker API and deploy your bot in minutes. TradePilot executes trades automatically while you monitor performance in real time.",
		JObVnYdT5:
			step1Discription ??
			props.JObVnYdT5 ??
			"Tell TradePilot what you want to achieve in plain language. For example, “Trade BTC with low risk.” No coding, no indicators, no technical configuration.",
		k6jl7bAAg: step1Img ??
			props.k6jl7bAAg ?? {
			pixelHeight: 1051,
			pixelWidth: 1604,
			src: "https://framerusercontent.com/images/b0ruEz3spIHTSi4xCfbfwoX2koM.png?scale-down-to=1024",
			srcSet:
				"https://framerusercontent.com/images/b0ruEz3spIHTSi4xCfbfwoX2koM.png?scale-down-to=512 512w,https://framerusercontent.com/images/b0ruEz3spIHTSi4xCfbfwoX2koM.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/b0ruEz3spIHTSi4xCfbfwoX2koM.png 1604w",
		},
		lwUnNPKD9: step1Heading ?? props.lwUnNPKD9 ?? "Describe Your Goal",
		pmpp7SCSB: step2Img ??
			props.pmpp7SCSB ?? {
			pixelHeight: 1020,
			pixelWidth: 1548,
			src: "https://framerusercontent.com/images/EPErbkkqsOxh8MmRFjfhCGP08.png?scale-down-to=1024",
			srcSet:
				"https://framerusercontent.com/images/EPErbkkqsOxh8MmRFjfhCGP08.png?scale-down-to=512 512w,https://framerusercontent.com/images/EPErbkkqsOxh8MmRFjfhCGP08.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/EPErbkkqsOxh8MmRFjfhCGP08.png 1548w",
		},
		Renab5ndj: step3Heading ?? props.Renab5ndj ?? "Go Live",
		rXU1jvem4: step2Heading ?? props.rXU1jvem4 ?? "Test & Validate",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "qm6JrJUbt",
		yICy65UuN:
			step2Discription ??
			props.yICy65UuN ??
			"Before going live, simulate your strategy on historical market data. See real performance metrics, risk behavior, and trade outcomes — clearly and transparently.",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React3.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		ffy1TjphS,
		A3R33WBVq,
		k6jl7bAAg,
		pmpp7SCSB,
		CtHiBo6zh,
		lwUnNPKD9,
		JObVnYdT5,
		rXU1jvem4,
		yICy65UuN,
		Renab5ndj,
		Gp0XQ20hc,
		...restProps
	} = getProps3(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "qm6JrJUbt",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const onAppear1nhcg4x = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("IjbyRy7KQ", true), 5e3);
	});
	const onAppearoi12l2 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("gsmeDGDZU", true), 5e3);
	});
	const onAppearpezwvd = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("NzJeMoZQz", true), 5e3);
	});
	const onAppearow1era = activeVariantCallback(async (...args) => {
		setVariant("qm6JrJUbt", true);
	});
	const vYMcHT6Mz12aluo5 = activeVariantCallback(async (...args) => {
		setVariant("qm6JrJUbt");
	});
	const vYMcHT6Mztj8vdf = activeVariantCallback(async (...args) => {
		setVariant("IjbyRy7KQ");
	});
	const vYMcHT6Mz1tbms0x = activeVariantCallback(async (...args) => {
		setVariant("gsmeDGDZU");
	});
	useOnVariantChange(baseVariant, {
		default: onAppear1nhcg4x,
		gsmeDGDZU: onAppearpezwvd,
		IjbyRy7KQ: onAppearoi12l2,
		NzJeMoZQz: onAppearow1era,
	});
	const sharedStyleClassNames = [className4, className3, className5];
	const scopingClassNames = cx3(serializationHash2, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["IjbyRy7KQ", "gsmeDGDZU"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "IjbyRy7KQ") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "gsmeDGDZU") return true;
		return false;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2
					value={transition12}
					{...addPropertyOverrides2(
						{
							NzJeMoZQz: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion3.div
						{...restProps}
						{...gestureHandlers}
						className={cx3(
							scopingClassNames,
							"framer-6xxbrk",
							"glass-1 to-transparent dark:glass-3 relative overflow-hidden rounded-2xl shadow-xl",
							className6,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Step 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"qm6JrJUbt"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color":
								"var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "none",
							"--border-top-width": "0px",
							backgroundColor: "transparent",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							boxShadow: "none",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								gsmeDGDZU: {
									"data-framer-name": "Step 3",
								},
								IjbyRy7KQ: {
									"data-framer-name": "Step 2",
								},
								NzJeMoZQz: {
									"data-framer-name":
										"Transition to 1 (Don't Change Content Here)",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<div className="via-foreground/60 absolute top-0 left-[10%] h-[1px] w-[80%] border-0 bg-gradient-to-r from-transparent to-transparent" />
						<motion3.div
							className={"framer-1b4ms37"}
							data-framer-name={"Top Steps Loader Wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"oJxhg3in8"}
						>
							<ComponentViewportProvider
								height={44}
								width={`calc(${componentViewport?.width || "100vw"} - 40px)`}
							>
								<SmartComponentScopedContainer
									className={"framer-vw2nf8-container"}
									layoutDependency={layoutDependency}
									layoutId={"MuvGlpWhm-container"}
									nodeId={"MuvGlpWhm"}
									rendersWithMotion={true}

									style={{
										opacity: 1,
									}}
									variants={{
										gsmeDGDZU: {
											opacity: 0.5,
										},
										IjbyRy7KQ: {
											opacity: 0.5,
										},
										NzJeMoZQz: {
											opacity: 1,
										},
									}}
								>
									{_jsx3(stdin_default3, {
										dDnGYdLN4: "STEP 1",
										height: "100%",
										id: "MuvGlpWhm",
										layoutId: "MuvGlpWhm",
										style: {
											width: "100%",
										},
										variant: "rObxpNGp_",
										vYMcHT6Mz: vYMcHT6Mz12aluo5,
										width: "100%",
										...addPropertyOverrides2(
											{
												gsmeDGDZU: {
													variant: "b88z41vz_",
												},
												IjbyRy7KQ: {
													variant: "b88z41vz_",
												},
												NzJeMoZQz: {
													variant: "b88z41vz_",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={44}
								width={`calc(${componentViewport?.width || "100vw"} - 40px)`}
							>
								<SmartComponentScopedContainer
									className={"framer-1g5v72j-container"}
									layoutDependency={layoutDependency}
									layoutId={"SjP6Njt5V-container"}
									nodeId={"SjP6Njt5V"}
									rendersWithMotion={true}

									style={{
										opacity: 0.5,
									}}
									variants={{
										IjbyRy7KQ: {
											opacity: 1,
										},
									}}
								>
									{_jsx3(stdin_default3, {
										dDnGYdLN4: "STEP 2",
										height: "100%",
										id: "SjP6Njt5V",
										layoutId: "SjP6Njt5V",
										style: {
											width: "100%",
										},
										variant: "b88z41vz_",
										vYMcHT6Mz: vYMcHT6Mztj8vdf,
										width: "100%",
										...addPropertyOverrides2(
											{
												IjbyRy7KQ: {
													variant: "rObxpNGp_",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<ComponentViewportProvider
								height={44}
								width={`calc(${componentViewport?.width || "100vw"} - 40px)`}
							>
								<SmartComponentScopedContainer
									className={"framer-1kvm0lm-container"}
									layoutDependency={layoutDependency}
									layoutId={"S_MzlEvup-container"}
									nodeId={"S_MzlEvup"}
									rendersWithMotion={true}

									style={{
										opacity: 0.5,
									}}
									variants={{
										gsmeDGDZU: {
											opacity: 1,
										},
									}}
								>
									{_jsx3(stdin_default3, {
										dDnGYdLN4: "STEP 3",
										height: "100%",
										id: "S_MzlEvup",
										layoutId: "S_MzlEvup",
										style: {
											width: "100%",
										},
										variant: "b88z41vz_",
										vYMcHT6Mz: vYMcHT6Mz1tbms0x,
										width: "100%",
										...addPropertyOverrides2(
											{
												gsmeDGDZU: {
													variant: "rObxpNGp_",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion3.div>
						<motion3.div
							className={"framer-1nzlp8x"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"OLEx8cLfZ"}
							style={{
								"--18ucmoc": ffy1TjphS === "column" ? "120%" : "1px",
								"--1m2uej8": ffy1TjphS === "column" ? void 0 : "1.2 0 0px",
								"--mm4la2": ffy1TjphS === "column" ? "100%" : "1px",
								"--uewguo": ffy1TjphS === "column" ? void 0 : "1 0 0px",
								"--yqxu0h": ffy1TjphS,
							}}
						>
							{A3R33WBVq && (
								<motion3.div
									className={"framer-b8i7qt"}
									data-framer-name={"Graphic Container"}
									layoutDependency={layoutDependency}
									layoutId={"j8yp4K6Qo"}
									style={{
										borderBottomLeftRadius: 30,
										borderBottomRightRadius: 30,
										borderTopLeftRadius: 30,
										borderTopRightRadius: 30,
									}}
								>
									<motion3.div
										className={"framer-17mbug4"}
										data-framer-name={"Image Background Fill Color"}
										layoutDependency={layoutDependency}
										layoutId={"cypoYxrrm"}
										style={{
											borderBottomLeftRadius: 23,
											borderBottomRightRadius: 23,
											borderTopLeftRadius: 23,
											borderTopRightRadius: 23,
										}}
									>
										{isDisplayed() && (
											<ImageWithFXWithOptimizedAppearEffect
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation}
												background={{
													alt: "",
													fit: "fit",
													pixelHeight: 2e3,
													pixelWidth: 2e3,
													sizes: `calc(${ffy1TjphS === "row" ? `max((${componentViewport?.width || "100vw"} - 40px) * 1.2, 1px)` : `calc((${componentViewport?.width || "100vw"} - 40px) * 1.2)`} - 24px)`,
													...toResponsiveImage(k6jl7bAAg),
													...{
														positionX: "left",
														positionY: "center",
													},
												}}
												className={"framer-noxl58"}
												data-framer-appear-id={"noxl58"}
												data-framer-name={"Image"}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"bOj0N_IQo"}
												optimized={true}
												style={{
													borderBottomLeftRadius: 20,
													borderBottomRightRadius: 20,
													borderTopLeftRadius: 20,
													borderTopRightRadius: 20,
												}}
											/>
										)}
										{isDisplayed1() && (
											<ImageWithFXWithOptimizedAppearEffect
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation}
												background={{
													alt: "",
													fit: "fit",
													pixelHeight: 2e3,
													pixelWidth: 2e3,
													...toResponsiveImage(pmpp7SCSB),
													...{
														positionX: "center",
														positionY: "center",
													},
												}}
												className={"framer-1yfdf44"}
												data-framer-appear-id={"1yfdf44"}
												data-framer-name={"Image"}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"Nqa9VtIbZ"}
												optimized={true}
												style={{
													borderBottomLeftRadius: 20,
													borderBottomRightRadius: 20,
													borderTopLeftRadius: 20,
													borderTopRightRadius: 20,
												}}
												{...addPropertyOverrides2(
													{
														IjbyRy7KQ: {
															background: {
																alt: "",
																fit: "fit",
																pixelHeight: 2e3,
																pixelWidth: 2e3,
																sizes: `calc((${ffy1TjphS === "row" ? `max((${componentViewport?.width || "100vw"} - 40px) * 1.2, 1px)` : `calc((${componentViewport?.width || "100vw"} - 40px) * 1.2)`} - 24px) * 0.95)`,
																...toResponsiveImage(pmpp7SCSB),
																...{
																	positionX: "center",
																	positionY: "center",
																},
															},
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
										)}
										{isDisplayed2() && (
											<ImageWithFXWithOptimizedAppearEffect
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation}
												background={{
													alt: "",
													fit: "fit",
													pixelHeight: 2e3,
													pixelWidth: 2e3,
													...toResponsiveImage(CtHiBo6zh),
													...{
														positionX: "center",
														positionY: "center",
													},
												}}
												className={"framer-n6r69v"}
												data-framer-appear-id={"n6r69v"}
												data-framer-name={"Image"}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"LlEMu36AA"}
												optimized={true}
												style={{
													borderBottomLeftRadius: 20,
													borderBottomRightRadius: 20,
													borderTopLeftRadius: 20,
													borderTopRightRadius: 20,
												}}
												{...addPropertyOverrides2(
													{
														gsmeDGDZU: {
															background: {
																alt: "",
																fit: "fit",
																pixelHeight: 2e3,
																pixelWidth: 2e3,
																sizes: `calc((${ffy1TjphS === "row" ? `max((${componentViewport?.width || "100vw"} - 40px) * 1.2, 1px)` : `calc((${componentViewport?.width || "100vw"} - 40px) * 1.2)`} - 24px) * 0.95)`,
																...toResponsiveImage(CtHiBo6zh),
																...{
																	positionX: "center",
																	positionY: "center",
																},
															},
														},
													},
													baseVariant,
													gestureVariant,
												)}
											/>
										)}
									</motion3.div>
								</motion3.div>
							)}
							<motion3.div
								className={"framer-n7yrct"}
								data-framer-name={"Text Content"}
								layoutDependency={layoutDependency}
								layoutId={"F8kgWac1N"}
							>
								{isDisplayed() && (
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-162pujd"}
										data-framer-name={"Title 1"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"uMt6A3jt6"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												className={"framer-styles-preset-qbxcjn"}
												data-styles-preset={"nf0yFfa08"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5)))",
												}}
											>
												{"01"}
											</motion3.p>
										</React3.Fragment>
									</RichText2>
								)}
								{isDisplayed1() && (
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-162pujd"}
										data-framer-name={"Title 2"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"uMt6A3jt6-2"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												className={"framer-styles-preset-qbxcjn"}
												data-styles-preset={"nf0yFfa08"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5)))",
												}}
											>
												{"02"}
											</motion3.p>
										</React3.Fragment>
									</RichText2>
								)}
								{isDisplayed2() && (
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-162pujd"}
										data-framer-name={"Title 3"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"uMt6A3jt6-3"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												className={"framer-styles-preset-qbxcjn"}
												data-styles-preset={"nf0yFfa08"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-5e357ad1-f56a-4886-be0b-ea13c633f85c, rgba(184, 199, 217, 0.5)))",
												}}
											>
												{"03"}
											</motion3.p>
										</React3.Fragment>
									</RichText2>
								)}
								{isDisplayed() && (
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-12u9cr6"}
										data-framer-name={"Title 1"}
										effect={textEffect}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"DS8R0wztW"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={lwUnNPKD9}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												className={"framer-styles-preset-i6z8by"}
												data-styles-preset={"j3hccNIu_"}
												style={{
													"--framer-text-alignment": "left",
												}}
											>
												{"Describe Your Goal"}
											</motion3.p>
										</React3.Fragment>
									</RichText2>
								)}
								{isDisplayed1() && (
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-6vwx8n"}
										data-framer-name={"Title 2"}
										effect={textEffect}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"t8lJvUm1J"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={rXU1jvem4}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												className={"framer-styles-preset-i6z8by"}
												data-styles-preset={"j3hccNIu_"}
												style={{
													"--framer-text-alignment": "left",
												}}
											>
												{"Test & Validate"}
											</motion3.p>
										</React3.Fragment>
									</RichText2>
								)}
								{isDisplayed2() && (
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-msyv49"}
										data-framer-name={"Title 3"}
										effect={textEffect}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"DUGpt3kX7"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={Renab5ndj}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												className={"framer-styles-preset-i6z8by"}
												data-styles-preset={"j3hccNIu_"}
												style={{
													"--framer-text-alignment": "left",
												}}
											>
												{"Go Live"}
											</motion3.p>
										</React3.Fragment>
									</RichText2>
								)}
								{isDisplayed() && (
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-1r60f0u"}
										data-framer-name={"discription 1"}
										effect={textEffect1}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"QRlXn8XIX"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											opacity: 0.6,
										}}
										text={JObVnYdT5}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												className={"framer-styles-preset-17f5k4v"}
												data-styles-preset={"rmSf_ipOK"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230)))",
												}}
											>
												"Tell TradePilot what you want to achieve in plain language. For example, “Trade BTC with low risk.” No coding, no indicators, no technical configuration."
											</motion3.p>
										</React3.Fragment>
									</RichText2>
								)}
								{isDisplayed1() && (
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-ojd3j5"}
										data-framer-name={"discription 2"}
										effect={textEffect1}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"hdEq8ViyQ"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											opacity: 0.6,
										}}
										text={yICy65UuN}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												className={"framer-styles-preset-17f5k4v"}
												data-styles-preset={"rmSf_ipOK"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230)))",
												}}
											>
												"Before going live, simulate your strategy on historical market data. See real performance metrics, risk behavior, and trade outcomes — clearly and transparently."
											</motion3.p>
										</React3.Fragment>
									</RichText2>
								)}
								{isDisplayed2() && (
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-1gd6iks"}
										data-framer-name={"discription 3"}
										effect={textEffect1}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"bp72Yn0ev"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											opacity: 0.6,
										}}
										text={Gp0XQ20hc}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React3.Fragment>
											<motion3.p
												className={"framer-styles-preset-17f5k4v"}
												data-styles-preset={"rmSf_ipOK"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230)))",
												}}
											>
												"Connect your broker API and deploy your bot in minutes. TradePilot executes trades automatically while you monitor performance in real time."
											</motion3.p>
										</React3.Fragment>
									</RichText2>
								)}
							</motion3.div>
						</motion3.div>
					</motion3.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css8 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-IlZB5.framer-1pqig7c, .framer-IlZB5 .framer-1pqig7c { display: block; }",
	".framer-IlZB5.framer-6xxbrk { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 20px; position: relative; width: 1000px; }",
	".framer-IlZB5 .framer-1b4ms37 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-IlZB5 .framer-vw2nf8-container, .framer-IlZB5 .framer-1g5v72j-container, .framer-IlZB5 .framer-1kvm0lm-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
	".framer-IlZB5 .framer-1nzlp8x { align-content: center; align-items: center; display: flex; flex: none; flex-direction: var(--yqxu0h); flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-IlZB5 .framer-b8i7qt { align-content: flex-start; align-items: flex-start; aspect-ratio: 1.3217821782178218 / 1; display: flex; flex: var(--1m2uej8); flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 151px); justify-content: center; overflow: visible; padding: 12px; position: relative; width: var(--18ucmoc); }",
	".framer-IlZB5 .framer-17mbug4 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 1px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-IlZB5 .framer-noxl58 { flex: none; height: 100%; overflow: visible; position: relative; width: 100%; z-index: 1; }",
	".framer-IlZB5 .framer-1yfdf44, .framer-IlZB5 .framer-n6r69v { flex: none; height: 95%; overflow: visible; position: relative; width: 95%; z-index: 1; }",
	".framer-IlZB5 .framer-n7yrct { align-content: flex-start; align-items: flex-start; display: flex; flex: var(--uewguo); flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 10px 10px 20px 10px; position: relative; width: var(--mm4la2); }",
	".framer-IlZB5 .framer-162pujd, .framer-IlZB5 .framer-12u9cr6, .framer-IlZB5 .framer-6vwx8n, .framer-IlZB5 .framer-msyv49 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-IlZB5 .framer-1r60f0u, .framer-IlZB5 .framer-ojd3j5, .framer-IlZB5 .framer-1gd6iks { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-IlZB5.framer-v-t16tf9 .framer-162pujd { order: 0; }",
	".framer-IlZB5.framer-v-t16tf9 .framer-6vwx8n { order: 2; }",
	".framer-IlZB5.framer-v-t16tf9 .framer-ojd3j5 { order: 5; }",
	...css5,
	...css3,
	...css6,
	'.framer-IlZB5[data-border="true"]::after, .framer-IlZB5 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerOLoUGThIY = withCSS3(Component3, css8, "framer-IlZB5");
var stdin_default4 = FramerOLoUGThIY;
FramerOLoUGThIY.displayName = "Process";
FramerOLoUGThIY.defaultProps = {
	height: 494,
	width: 1e3,
};
addPropertyControls3(FramerOLoUGThIY, {
	variant: {
		options: ["qm6JrJUbt", "IjbyRy7KQ", "gsmeDGDZU", "NzJeMoZQz"],
		optionTitles: [
			"Step 1",
			"Step 2",
			"Step 3",
			"Transition to 1 (Don't Change Content Here)",
		],
		title: "Variant",
		type: ControlType3.Enum,
	},
	ffy1TjphS: {
		defaultValue: "row",
		displaySegmentedControl: true,
		optionIcons: ["direction-horizontal", "direction-vertical"],
		options: ["row", "column"],
		optionTitles: ["Horizontal", "Vertical"],
		title: "Direction 3",
		type: ControlType3.Enum,
	},
	A3R33WBVq: {
		defaultValue: true,
		title: "images visible",
		type: ControlType3.Boolean,
	},
	k6jl7bAAg: {
		__defaultAssetReference:
			"data:framer/asset-reference,b0ruEz3spIHTSi4xCfbfwoX2koM.png?originalFilename=Group+28DSD9255.png&preferredSize=auto",
		title: "step1 img",
		type: ControlType3.ResponsiveImage,
	},
	pmpp7SCSB: {
		__defaultAssetReference:
			"data:framer/asset-reference,EPErbkkqsOxh8MmRFjfhCGP08.png?originalFilename=GrouSDSp+289247.png&preferredSize=auto",
		title: "step2 img",
		type: ControlType3.ResponsiveImage,
	},
	CtHiBo6zh: {
		__defaultAssetReference:
			"data:framer/asset-reference,0DBAix0ysUgnw6WhKOms5oGcN8.png?originalFilename=Group+28SA9248.png&preferredSize=auto",
		title: "step3 img",
		type: ControlType3.ResponsiveImage,
	},
	lwUnNPKD9: {
		defaultValue: "Start by Entering Your Data",
		displayTextArea: false,
		title: "step1 heading",
		type: ControlType3.String,
	},
	JObVnYdT5: {
		defaultValue:
			"Easily upload your marketing data or integrate your CRM, social media, and email platforms. Our AI effortlessly syncs and organizes everything for a smooth analysis process.",
		displayTextArea: true,
		title: "step1 discription",
		type: ControlType3.String,
	},
	rXU1jvem4: {
		defaultValue: "Let AI Analyze & Optimize",
		displayTextArea: false,
		title: "step2 heading",
		type: ControlType3.String,
	},
	yICy65UuN: {
		defaultValue:
			"Upload your marketing data or connect your existing tools like CRM, social media, and email platforms. Our AI automatically syncs and organizes everything for seamless analysis.",
		displayTextArea: true,
		title: "step2 discription",
		type: ControlType3.String,
	},
	Renab5ndj: {
		defaultValue: "Receive Actionable Results",
		displayTextArea: false,
		title: "step3 heading",
		type: ControlType3.String,
	},
	Gp0XQ20hc: {
		defaultValue:
			"Upload your marketing data or connect your existing tools like CRM, social media, and email platforms. Our AI automatically syncs and organizes everything for seamless analysis.",
		displayTextArea: true,
		title: "step3 discription",
		type: ControlType3.String,
	},
});
addFonts2(
	FramerOLoUGThIY,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ComponentStepFonts,
		...getFontsFromSharedStyle2(fonts4),
		...getFontsFromSharedStyle2(fonts3),
		...getFontsFromSharedStyle2(fonts5),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/WGx9YFtUrCsxprs6fne5/rlWAijSNN5LdY0P67X6K/m7MVr9wQx.js
var ElementsBadgeFonts = getFonts2(stdin_default);
var SmartComponentScopedContainerWithFX = withFX2(
	SmartComponentScopedContainer2,
);
var RichTextWithFX = withFX2(RichText3);
var ProcessFonts = getFonts2(stdin_default4);
var serializationHash3 = "framer-ISK0O";
var variantClassNames3 = {
	MycauY9Gj: "framer-v-k3k5qq",
};
var transition13 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition22 = {
	damping: 60,
	delay: 0.3,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var transition32 = {
	damping: 60,
	delay: 0.4,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var transition42 = {
	damping: 60,
	delay: 0.5,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var transition52 = {
	damping: 60,
	delay: 0.6,
	mass: 1,
	stiffness: 320,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition3 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext3);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext3.Provider value={contextValue}>
			{children}
		</MotionConfigContext3.Provider>
	);
};
var Variants3 = motion4.create(React4.Fragment);
var getProps4 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency3 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo3();
	const componentViewport = useComponentViewport3();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		...restProps
	} = getProps4(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState3({
		defaultVariant: "MycauY9Gj",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames3,
	});
	const layoutDependency = createLayoutDependency3(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx4(serializationHash3, ...sharedStyleClassNames);
	return (
		<LayoutGroup3 id={layoutId ?? defaultLayoutId}>
			<Variants3 animate={variants} initial={false}>
				<Transition3 value={transition13}>
					<motion4.div
						{...restProps}
						{...gestureHandlers}
						className={cx4(
							scopingClassNames,
							"framer-k3k5qq",
							className6,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"MycauY9Gj"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider2
							height={29}
							y={(componentViewport?.y || 0) + 0}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition22,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation3}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-15v5k5t-container"}
								layoutDependency={layoutDependency}
								layoutId={"lfdwEZGXx-container"}
								nodeId={"lfdwEZGXx"}
								rendersWithMotion={true}

								transformTemplate={transformTemplate1}
							>
								{_jsx4(stdin_default, {
									GJdJmFCj5: "PROCESS",
									height: "100%",
									id: "lfdwEZGXx",
									layoutId: "lfdwEZGXx",
									v7319IK7C: stdin_default2,
									width: "100%",
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider2>
						<RichTextWithFX
							__framer__animate={{
								transition: transition32,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation3}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__fromCanvasComponent={true}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-1h3nx59"}
							fonts={["Inter-Medium", "GF;Instrument Serif-italic"]}
							layoutDependency={layoutDependency}
							layoutId={"igjyaI8xo"}
							style={{
								"--extracted-1of0zx5":
									"var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React4.Fragment>
								<motion4.h2
									style={{
										"--font-selector": "SW50ZXItTWVkaXVt",
										"--framer-font-size": "44px",
										"--framer-font-weight": "500",
										"--framer-text-alignment": "center",
										"--framer-text-color":
											"var(--extracted-1of0zx5, var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230)))",
									}}
								>
									<motion4.span
										data-text-fill={"true"}
										style={{
											backgroundImage:
												"linear-gradient(138deg, var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230)) 51.657657657657666%, var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13)) 166%)",
										}}
									>
										{"Our Simple & "}
										<motion4.span
											style={{
												"--font-selector":
													"R0Y7SW5zdHJ1bWVudCBTZXJpZi1pdGFsaWM=",
												"--framer-font-family":
													'"Instrument Serif", "Instrument Serif Placeholder", serif',
												"--framer-font-style": "italic",
												"--framer-font-weight": "400",
											}}
										>
											{"Smart Process"}
										</motion4.span>
									</motion4.span>
								</motion4.h2>
							</React4.Fragment>
						</RichTextWithFX>
						<RichTextWithFX
							__framer__animate={{
								transition: transition42,
							}}
							__framer__animateOnce={true}
							__framer__enter={animation3}
							__framer__styleAppearEffectEnabled={true}
							__framer__threshold={0}
							__fromCanvasComponent={true}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							className={"framer-1kfgrkv"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"k_RFahnHR"}
							style={{
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React4.Fragment>
								<motion4.p
									className={"framer-styles-preset-1kvyxmc"}
									data-styles-preset={"n7RLEGRKm"}
									style={{
										"--framer-text-alignment": "center",
									}}
								>
									{
										"Everything you need to collaborate, create, and scale, all in one place."
									}
								</motion4.p>
							</React4.Fragment>
						</RichTextWithFX>
						<ComponentViewportProvider2
							height={494}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 716) -
								494
							}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition52,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation3}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-ueuzad-container"}
								layoutDependency={layoutDependency}
								layoutId={"VlV2lpRVs-container"}
								nodeId={"VlV2lpRVs"}
								rendersWithMotion={true}

							>
								{_jsx4(stdin_default4, {
									A3R33WBVq: true,
									CtHiBo6zh: addImageAlt(
										{
											pixelHeight: 1011,
											pixelWidth: 1536,
											src: "https://framerusercontent.com/images/T5LD7i0AQslhhwPvWrkU4ENnc.png?width=1536&height=1011",
											srcSet:
												"https://framerusercontent.com/images/T5LD7i0AQslhhwPvWrkU4ENnc.png?scale-down-to=512&width=1536&height=1011 512w,https://framerusercontent.com/images/T5LD7i0AQslhhwPvWrkU4ENnc.png?scale-down-to=1024&width=1536&height=1011 1024w,https://framerusercontent.com/images/T5LD7i0AQslhhwPvWrkU4ENnc.png?width=1536&height=1011 1536w",
										},
										"",
									),
									ffy1TjphS: "row",
									Gp0XQ20hc:
										"Deploy the bot to live or demo trading. Track trades, profit, drawdown, and decisions in a real-time dashboard.",
									height: "100%",
									id: "VlV2lpRVs",
									JObVnYdT5:
										"Connect your broker API and deploy your bot in minutes. TradePilot executes trades automatically while you monitor performance in real time.",
									k6jl7bAAg: addImageAlt(
										{
											pixelHeight: 1048,
											pixelWidth: 1602,
											src: "https://framerusercontent.com/images/b0ruEz3spIHTSi4xCfbfwoX2koM.png?scale-down-to=1024",

										},
										"",
									),
									layoutId: "VlV2lpRVs",
									lwUnNPKD9: "Describe Your Goal",
									pmpp7SCSB: addImageAlt(
										{
											pixelHeight: 1124,
											pixelWidth: 1808,
											src: "https://framerusercontent.com/images/NlShinj3SRLiU2GpzFKbH8loPs.png?width=1808&height=1124",
											srcSet:
												"https://framerusercontent.com/images/NlShinj3SRLiU2GpzFKbH8loPs.png?scale-down-to=512&width=1808&height=1124 512w,https://framerusercontent.com/images/NlShinj3SRLiU2GpzFKbH8loPs.png?scale-down-to=1024&width=1808&height=1124 1024w,https://framerusercontent.com/images/NlShinj3SRLiU2GpzFKbH8loPs.png?width=1808&height=1124 1808w",
										},
										"",
									),
									Renab5ndj: "Go Live",
									rXU1jvem4: "Test & Validate",
									style: {
										width: "100%",
									},

									width: "100%",
									yICy65UuN:
										"Before going live, simulate your strategy on historical market data. See real performance metrics, risk behavior, and trade outcomes clearly and transparently.",
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider2>
					</motion4.div>
				</Transition3>
			</Variants3>
		</LayoutGroup3>
	);
});
var css9 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ISK0O.framer-a9yi1r, .framer-ISK0O .framer-a9yi1r { display: block; }",
	".framer-ISK0O.framer-k3k5qq { height: 716px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1120px; }",
	".framer-ISK0O .framer-15v5k5t-container { flex: none; height: auto; left: 50%; position: absolute; top: 0px; width: auto; }",
	".framer-ISK0O .framer-1h3nx59 { flex: none; height: auto; left: 50%; position: absolute; top: 39px; white-space: pre-wrap; width: 640px; word-break: break-word; word-wrap: break-word; }",
	".framer-ISK0O .framer-1kfgrkv { flex: none; height: auto; left: 50%; position: absolute; top: 102px; white-space: pre-wrap; width: 640px; word-break: break-word; word-wrap: break-word; }",
	".framer-ISK0O .framer-ueuzad-container { bottom: 0px; flex: none; height: auto; left: 0px; position: absolute; right: 0px; }",
	...css,
];
var Framerm7MVr9wQx = withCSS4(Component4, css9, "framer-ISK0O");
var stdin_default5 = Framerm7MVr9wQx;
Framerm7MVr9wQx.displayName = "smart process";
Framerm7MVr9wQx.defaultProps = {
	height: 716,
	width: 1120,
};
addFonts3(
	Framerm7MVr9wQx,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Instrument Serif",
					source: "google",
					style: "italic",
					uiFamilyName: "Instrument Serif",
					url: "https://fonts.gstatic.com/s/instrumentserif/v5/jizHRFtNs2ka5fXjeivQ4LroWlx-6zATjnTNgNq55w.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ElementsBadgeFonts,
		...ProcessFonts,
		...getFontsFromSharedStyle3(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:smart-process
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e6ca028d8dcade9bd82279484f423380160c521ae9704eaaee26e5448359232b"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SmartProcessFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"e6ca028d8dcade9bd82279484f423380160c521ae9704eaaee26e5448359232b"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var smart_process_default = ComponentWithRoot;
export { smart_process_default as default };
